### ISSUE TITLE
Ways to map multiple gestures to the same command

### ISSUE THREAD

**Issue by lewisaronmilne** [marklieberman/foxygestures#100]
This would be useful in general but a specific use case would be symmetrical gestures such as up-down and down-up (I would like to map these both to reload).

There was a bug in my old gesture add-on that allowed for this and I used it extensively.

**Comment by marklieberman** [comment]
See #54 and #90. I'm not going to support this in the near future because I don't have time to rewrite a significant chunk of the UI, but there is a simple workaround. You can use a user script with the alternative gesture and call the built in command.
```js
executeInBackground(data => commandReload(data), [ data ]);
```

**Comment by lewisaronmilne** [comment]
I'll probably do this thanks.
