### ISSUE TITLE
New action: "Open link in new tab | Open new tab"

### ISSUE THREAD

**Issue by rodalpho** [marklieberman/foxygestures#101]
When the action "open link in new tab" is executed and the cursor is not over a link, nothing happens. I would like the option to instead open a new tab. This would apply to the "open link in background tab" action as well. This was possible in Firegestures.

**Comment by rodalpho** [comment]
Thanks to a kind user on reddit, this userscript works. I do believe it belongs as a default action in the addon, as it's a pretty common usecase.

```
if (data.element.linkHref) { 
    executeInBackground(data => commandOpenLinkInNewForegroundTab(data), [ data ]); 
} else { 
    executeInBackground(data => commandNewTab(data), [ data ]); 
}
```

**Comment by marklieberman** [comment]
FYI that kindly Reddit user is me. I should get verified on /r/firefox.

**Comment by rodalpho** [comment]
Oh, nice! Thanks again for the script.

**Comment by jasiukaruzela** [comment]
And may I ask for the same but for new windows?
Also to be opened in the background (that is I don't jump to the newly opened window).
thanks

**Comment by soultemptation** [comment]
Thank you very much for this snipped. I had the same, but less elegant:
`var link = data.element.linkHref ? data.element.linkHref : "https://duckduckgo.com/";
var win = window.open(link, '_blank');
win.focus();`
The main problem is, that the popup gets blocked by Firefox by default. You need to allow it once for it to work.

@jasiukaruzela: Have you tried the following:
`if (data.element.linkHref) { 
    executeInBackground(data => commandOpenLinkInNewWindow(data), [ data ]); 
} else { 
    executeInBackground(data => commandNewWindow(data), [ data ]); 
}`

**Comment by jasiukaruzela** [comment]
Thank you very much Good Man :)
