### ISSUE TITLE
Closes wrong tab if using more than one window

### ISSUE THREAD

**Issue by rageix** [marklieberman/foxygestures#103]
Windows 10. Firefox 57.0. Foxy Gestures 1.0.11.

1. Create a new tab, tear it out in to a new window. Or just create a new window.
2. (optional) You can also create multiple tabs in the new window and this will affect all of them.
3. Go back to original window and try and close a tab with a gesture.

What is expected: The tab that is currently active in the old window closes.

What happens: The tabs in your new window will close in order of newest to oldest until they all are closed.

**Comment by marklieberman** [comment]
I can't reproduce this using 56 or 57. I'm just getting the [active tabs for the current window](https://github.com/marklieberman/foxygestures/blob/master/src/background/commands.js#L295) then [closing it](https://github.com/marklieberman/foxygestures/blob/master/src/background/commands.js#L357). Nothing much to go wrong.

**Comment by rageix** [comment]
I tried it on a different computer and it did not happen. I then totally wiped Firefox and all settings and extensions, and reinstalled and everything works fine. I wonder if some how an old legacy mouse gesture plugin was some how affecting the new stuff. 

Either way problem solved and thanks for looking it to it.
