### ISSUE TITLE
Doesn't work with Firefox 57

### ISSUE THREAD

**Issue by fetis** [marklieberman/foxygestures#104]
Hello. I've just updated to the latest FF 57.0 and this extension supposed to be a replacement for gestures (I've used Mouse Gestures Suite). Unfortunately it doesn't work for me. Multiple issues

- Settings shows blank page
- Gestures don't work. I see a drawn line, but nothing happened and context menu popups.

**Comment by marklieberman** [comment]
Can you open the browser console and look for an error? Ctrl+Shift+J.

**Comment by khromov** [comment]
+1 same issue. Should be easy to reproduce.

**Comment by marklieberman** [comment]
I've been using it on FF57+ on one of my machines since it was in nightly. I tried it this morning on my machine that was running FF56 and then after updating to FF57 and it was working. 

Open the browser console and tell if it gives you errors. 

Can you guys try a new profile? It might be storage.sync issues.

You have to give me something to work with besides "it doesn't work".

**Comment by m4DnZ** [comment]
I've got the same issue with the blank settings page. I'm no coder so can't really help with that and I tried to look at the console to see what's wrong but I couldn't figure out what you needed from it so I just took a screenshot :P 
![image](https://user-images.githubusercontent.com/17184031/32799788-5a6f6bb4-c981-11e7-98f1-fc6976d4f807.png)

**Comment by marklieberman** [comment]
It looks similar to #76 which seemed to be an issue with the sync API in Firefox. I need you guys to try a fresh profile.

https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by jrappen** [comment]
Cannot reproduce, works fine here.

* FoxyGestures 1.0.11
* FF 57 x64 portable
* Win10 Pro x64 1709

**Comment by stephanfriedrich** [comment]
i had the same issue like #issuecomment-344367543 after delete and create new profile, the f_oxy gestures options site_ works fine

**Comment by stephanfriedrich** [comment]
with ff58 dev edition on linux, right-click gesture works, but additionally right-click-browser-menu will opened too

**Comment by fetis** [comment]
Somehow I managed it to work, but I don't know how. 

I have context menu opened on every gesture. Is it expected behaviour for now?

**Comment by stephanfriedrich** [comment]
@fetis its the same behaviour for Foxy Gestures 1.0.11 with context menue open.

**Comment by marklieberman** [comment]
@stephanfriedrich Read the addon description its the very first thing written there. RIght-click is currently not working on OSX/Linux due to Firefox limitations.

**Comment by lewisaronmilne** [comment]
I intermittently have this issue. It went but comes back occasionally.

Also once all of my userscripts disappeared. They still worked which meant it was an issue with options page which makes me think it's the same issue.

**Comment by pmorch** [comment]
Ahhh damn... my [comment](https://github.com/marklieberman/foxygestures/issues/76#issuecomment-344940840) in #76 should've been entered here...

**Comment by marklieberman** [comment]
@lewisaronmilne I've already fixed the issue with the user scripts page not working, its just not published yet. That was a separate thing. 

This issue is something probably funny in the promise chain that loads the settings from storage.sync.

**Comment by protist** [comment]
I have two systems running Firefox, both derived from the same profile directory (originally from Firefox 56). Both are running Linux, Firefox 57. On one system, Foxy Gestures works perfectly, with no problems at all.

On the other, Foxy Gestures fails intermittently. Initially, I could configure the add-on, but subsequently it stopped working. The preference page was blank, and CPU usage rises to >200% of a core. Also, when I try to quit Firefox, all windows close, Firefox stalls for a couple of minutes, then shows me the crash screen. If I disable Foxy Gestures, CPU usage is low again, and Firefox quits fine.

I tried creating a new, empty profile, and could immediately replicate this issue. I installed Foxy Gestures, and without restarting. CPU usage spiked, and I couldn't access Foxy Gesture's preferences. I opened the console (Ctrl+Shift+J) which didn't seem particularly informative. Here is a screenshot.

![Empty profile](https://user-images.githubusercontent.com/646668/33055297-cc46dd3e-ced2-11e7-9ff4-f7915ddc4a5f.png)

FWIW I then quit/crashed as above, but on ~3 subsequent restarts into this new profile, Foxy Gestures worked every time.

**Comment by protist** [comment]
On a whim, I tried again this morning, and it works perfectly. 🤷

Preferences are accessible, and gestures work (but presumably this won't last).

**Comment by t0lik** [comment]
I have FF 57 on Windows 8.1 and I just have done "Refresh" function in FF and after that I install Foxy Gestures 1.0.13. The settings page still remains black, console messages look like those ones in the @m4DnZ [message](https://github.com/marklieberman/foxygestures/issues/104#issuecomment-344367543)

**Comment by n3ko** [comment]
The latest 1.0.14 version fixed my FF57 issues. -- FF 57.0 (64bit) Ubuntu

**Comment by t0lik** [comment]
The same issue on 1.0.14 FF 57 Win 8.1 x64.

**Comment by t0lik** [comment]
This issue has gone after updating FF to 57.0.1

**Comment by fetis** [comment]
but instead, I've got another issue. Context menu doesn't open on right click anymore.

**Comment by marklieberman** [comment]
@fetis OSX/Linux? Do you have double right-click enabled in options. Thats new in 1.0.14.

**Comment by fetis** [comment]
@marklieberman I'm on OSX. I have this option enabled and double click works fine. So, is any chance to have the normal right click, rather than double?

**Comment by pmorch** [comment]
Sergey, as described in #67 this is the best that can be done with FF57 on
Linux and OSX at the moment. See issue #67 for more info...

**Comment by marklieberman** [comment]
@fetis FF59 will be the first release version of FF with the ability to have a normal right click on OSX/Linux. (It's behind a about:config pref on FF58 beta) See: https://bugzilla.mozilla.org/show_bug.cgi?id=1360278

**Comment by fetis** [comment]
@marklieberman that's a pity, but it's a Firefox issue. I think we can close the issue
