### ISSUE TITLE
Doesnt work on new tab

### ISSUE THREAD

**Issue by darkzerp** [marklieberman/foxygestures#105]
As in title the foxy doesn't work on new tab in FF 57.0 I can't change pages or close new tabs, if its www sites than I can do all other commends but in new tab all functions doesnt work. Could you fix this ? As i sometimes have few new tabs but want to close them later with foxy, now I can't do this ;/
It also doesnt work on https://addons.mozilla.org

**Comment by jdreesen** [comment]
Please read https://github.com/marklieberman/foxygestures#limitations
Sadly, there's nothing @marklieberman  can do.

**Comment by darkzerp** [comment]
What a shame it wont work ;/ 
Anyway thanks for help :)
