### ISSUE TITLE
New Gesture Suggestion: Go To Home Page

### ISSUE THREAD

**Issue by TryCatch22** [marklieberman/foxygestures#106]
As a long-time user of FireGestures, I've now migrated to FoxyGestures thanks to its better gesture editing UI and FF57 support (thanks for that!)

The one thing I'm missing to be completely happy is a gesture for Go To Home Page (e.g. Google in my case).

**Comment by marklieberman** [comment]
See #65.

**Comment by TryCatch22** [comment]
Thanks for the link, that worked perfectly. Apologies for not finding the above by myself. I swear I searched for it but GitHub defaults to searching only for open issues!

If I may make a further suggestion, I feel that "navigating to a particular page" is a popular enough use case that listing a sample userscript directly in the README.md would be helpful for people like me.
