### ISSUE TITLE
New Action: Maximize/restore window

### ISSUE THREAD

**Issue by wysiwygbg** [marklieberman/foxygestures#107]
Hello,

Since today's release of FF57, people are bound to move to some new add-ons, and this is the add-on to move to from the old FireGestures add-on. However there are some things that are still not available for FoxyGestures to be a complete substitute.

One thing that will be very useful to people is - under the "Other Gestures" tab people can enable "Chord Gestures", but currently the "command list" is very limited. It will be great if  you can add a user macro or as it was in FireGestures - the user could choose any of the commands available through the FireFox Menu Bar. I personally use Right click + Left click = F11 = enable/disable Full Screen mode, which currently can't be done with FoxyGestures.

Also the add-on currently does not work at all on a New Tab or in its own Options applet or anywhere in the Add-ons Manager applet, which means if a user wants to use the "Undo Close" gesture when he's on any of those pages, he can't. FireGestures worked everywhere, so this new add-on should also work the same way.

Thank you for the great new add-on and I hope you add the upmentioned functionality soon.

-wysiwyg

**Comment by marklieberman** [comment]
> It will be great if you can add a user macro or as it was in FireGestures
If you create a user script, it will appear in the select list for chord and wheel commands.

> enable/disable Full Screen mode, which currently can't be done with FoxyGestures
I can add a built in command to do this.

> Also the add-on currently does not work at all on a New Tab or in its own Options applet or anywhere in the Add-ons Manager applet
This is a web extensions limitation and it's written in the addon description. I cannot do everything that FireGestures can do because of different addon technology.
