### ISSUE TITLE
Gestures dosn't work on Interal Pages

### ISSUE THREAD

**Issue by Athesis** [marklieberman/foxygestures#112]
Hi,

I gut the new Firefox-Update (57.0 x64) and updated from FireGestures to Foxy Gestures. I just have one issue: Gestures dosn't work on Firefox-Internal pages like "Website not found", the "Firefox Startpage" and any other internal page. I would love to see Foxy Gestures working on these, too! 

Thankyou
~Athesis

**Comment by jdreesen** [comment]
Webextensions do not support this.
See: https://github.com/marklieberman/foxygestures#limitations
