### ISSUE TITLE
Focus of next display tab after close current tab not always consistent

### ISSUE THREAD

**Issue by vigermam** [marklieberman/foxygestures#113]
The focus of next display tab after using gesture to close tabs is not always consistent.

for example, 

- if using the middle mouse button to click on link to open a new tab, after the close gesture, the active tab will be "previous" tab

- if using the custom script to open the tab, like [this,](https://github.com/marklieberman/foxygestures/issues/93#issuecomment-343701618) then after close gesture,the active tab will be "right side" tab

**Comment by marklieberman** [comment]
I don't control the focus when closing a tab. I just call `browser.tabs.close(tabId)` and Firefox does the rest. Maybe #114 will improve the situation.

**Comment by marklieberman** [comment]
I am closing this because #139 should cover it. Anyway, I've implemented #114 so maybe it will be fixed.
