### ISSUE TITLE
Specify 'openerTabId' when creating new tabs

### ISSUE THREAD

**Issue by Andikki** [marklieberman/foxygestures#114]
This add-on doesn't work well with [Tree Style Tab](https://addons.mozilla.org/firefox/addon/tree-style-tab/) add-on.  
When a link is opened in a new tab via a context menu, it gets opened as a child tab in a tree. But when using gestures, the new tabs are opened at the top level of the tree, which is inconvenient.

I'm guessing that no `openerTabId` is provided when opening a new tab with Foxy Gestures, as detailed in [Mozilla documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create) or [the issue at Tree Style Tab github](https://github.com/piroor/treestyletab/issues/1413).

**Comment by marklieberman** [comment]
Thats likely, as openerTabId was not implemented when I started writing Foxy Gestures. I will investigate.
