### ISSUE TITLE
cord gestures do not work 

### ISSUE THREAD

**Issue by tomchiverton** [marklieberman/foxygestures#119]
right-left always just brings up the right click menu, does not (for instance) navigate back in history

**Comment by AGCaesar** [comment]
It is the same issue all gestures have on Linux/MacOS

**Comment by tomchiverton** [comment]
fireGestures worked (yes, yes, I know, this is a WebExtension and it wasn't). 

if it plain does not work, then the feature should be removed from the plug-in till FireFox is fixed ?

**Comment by AGCaesar** [comment]
It works on Windows. Where is a workaround for Linux, see issue #109

**Comment by tomchiverton** [comment]
I've read the linked bug. I do not see the workaround steps ?

**Comment by AGCaesar** [comment]
The workaround is to install the package build by @fotcorn
Or just wait 2-3 days
