### ISSUE TITLE
Open new window

### ISSUE THREAD

**Issue by jasiukaruzela** [marklieberman/foxygestures#120]
Once this gesture is executed, it first opens a new tab and then only "moves" it to the new window.

**Comment by marklieberman** [comment]
It's done that way because I want to preserve the cookieStoreID (for containers) but I can't do it in one API call. So, I have to create the tab and only then move it to a new window.

**Comment by jdreesen** [comment]
This results in another tab (the last one) being focused in the old window after the gesture, when the tab where the gesture was performed was not the last one, which I find really annoying.

(Maybe this will be fixed with #114?)

**Comment by jasiukaruzela** [comment]
Cannot it be like in the FireGestures?
