### ISSUE TITLE
Missing Previous Tab with scroll wheel

### ISSUE THREAD

**Issue by Feuerhai** [marklieberman/foxygestures#122]
It is possible to go to the next or previous tab with mouse gestures, but with the scroll wheel you can only choose going to the next tab. Did you just forget to add it or is there a problem with the implementation?

I really like this addon, even if it isn't possible.

**Comment by marklieberman** [comment]
![screen shot 2017-11-16 at 11 48 01 am](https://user-images.githubusercontent.com/6473247/32903836-0bc35bbc-cac4-11e7-8790-dcf7224a1c7b.png)

It's there ,just the commands are sorted alphabetically. I'll implement categories in the list at a later date.

**Comment by Feuerhai** [comment]
Sorry, I'm an Idiot. I didn't see the scroll bar because my window is too wide and I only looked on the left side.
![2017-11-16 17_52_21-foxy gestures options](https://user-images.githubusercontent.com/25032400/32904143-16b642b8-caf7-11e7-8b78-2e19da6725f0.png)
