### ISSUE TITLE
New Action: Move Up/Parent Dir

### ISSUE THREAD

**Issue by JDHannan** [marklieberman/foxygestures#123]
FireGestures had one thing that I used quite a bit, where it would move you up one level in the address

if you were at www.webpage.com/subfolder - it would take you to www.webpage.com

It would be great if that were part of this! Thanks!

**Comment by JDHannan** [comment]
I got antsy and figured out how to do this with a user script in the meantime.  For anyone else wanting this, it almost couldn't be easier:
window.location.href = '../'; //one level up

**Comment by ThiefMaster** [comment]
Doesn't work properly. For example, if I run `window.location.href = '../';` in the console on this page, I go from (1) to (2) instead of (3)

```
(1) https://github.com/marklieberman/foxygestures/issues/123
(2) https://github.com/marklieberman/foxygestures/
(3) https://github.com/marklieberman/foxygestures/issues/
```

**Comment by c01o** [comment]
also kill subdomains like firegestures did:

```js
let isDir = window.location.href.endsWith('/');
let isRoot = window.location.pathname === '/';
let getUpperLevelDomain = (hostname) => hostname.split('.').slice(1).join('.');

isRoot ? window.location.hostname = getUpperLevelDomain(window.location.hostname)
       : window.location.href = (isDir ? '..' : './');
```

https://gist.github.com/c01o/cd174e51e1c288889149034b21722643

**Comment by marklieberman** [comment]
@c01o Thanks for the script it helped me implement this command quickly. I added a rudimentary check if it reached the TLD just to avoid trying to navigate to http://com or http://co.uk, etc.
