### ISSUE TITLE
Feature gesture request: Remove element in page.

### ISSUE THREAD

**Issue by Light-Code** [marklieberman/foxygestures#124]
Hi.
As many similar requests here, mine also will be about a feature that was available with the FireGestures addon. This user script allowed the user to simply remove anything form a loaded page. It was great for many cases where there was an obstructing invisible element (bug or some leftovers from adblock's add removal) blocking you from using the page. It would be really good if someone could "translate" the FireGestures script into a Foxy Gestures one. Below is the original script from xuldev.org.

`var node = FireGestures.sourceNode;`
`node.parentNode.removeChild(node);`

Thanks in advance.

**Comment by marklieberman** [comment]
Try this user script for now:
```
let node = mouseDown.target;
node.parentNode.removeChild(node);
```

**Comment by Light-Code** [comment]
Thanks @marklieberman !
The user script works great. 

By the way, wouldn't it be great to have a place where such scripts could be published for other users? FireGestures had [xuldev.org repo](http://www.xuldev.org/firegestures/getscripts.php) for that. 

Cheers.
