### ISSUE TITLE
Context menu on double right click

### ISSUE THREAD

**Issue by wollistik** [marklieberman/foxygestures#126]
Hi,
I really appreciate this extension, but since I am a Linux user, I am currently struggling with the Context-Menu-On-Right-Button-Limitation...

I found another gesture extension, that has a quiet nice workaround for this problem:
The context menu is triggered only on double right click, so mouse gestures with right mouse button work. Unfortunately this extension is very basic and has no customization options, so I would be glad to see this feature in Foxy Gestures too.

This feature would be an adequate compromise until FF has solved the problem.

Here's the link to extension website:
https://addons.mozilla.org/en-US/firefox/addon/mouse-gestures/

And the link to the sources:
https://gestures.wmux.ru/source-code/

Cheers

**Comment by marklieberman** [comment]
There's a PR for this #109 that will be merged soon.

**Comment by wollistik** [comment]
Very nice!
+1
