### ISSUE TITLE
middle button often starts with R

### ISSUE THREAD

**Issue by jerry1970** [marklieberman/foxygestures#128]
Although I was used to using the right mouse button for gestures, FF showing the right-click menu (Xubuntu 17.04, Firefox 57) is so annoying that I switched to using the middle button (a wheel in my case).

But many times (not always, have not been able to find out yet when), when I start the gesture by clicking the middle button, it starts with a gestures I did not do. The following screenshot (dark theme, gesture path is green) shows when I clicked and moved left. Right after I clicked, the green line pointing to somewhere outside the viewport, the gesture tip shows R; I moved to the left, the gesture tip shows RL. The gesture path is not updated, as if it was outside the viewport.

![image](https://user-images.githubusercontent.com/5627407/32938736-7a9f68d2-cb7d-11e7-8f60-9657066d5453.png)

Remarkable: when I start the gesture near the left side of the page, the first gesture is D instead of R and the farther I go to the right of the page to start the gesture, the farther the green line point to the right.

I tried moving the FF window to another monitor but that has not effect.

**Comment by marklieberman** [comment]
First thing to try is make sure that Preferences > General > Browsing > "Use autoscrolling" in Firefox is disabled.

**Comment by jerry1970** [comment]
Yes, that works, thanks!

Now I notice that while gesturing with the mouse wheel, the page does react to the wheel as well so a longer gesture might involve some scrolling of the page as well, although the gesture path remains on the same place. Not a problem for me but just to be clear.
