### ISSUE TITLE
Suggestion: start gesture with key

### ISSUE THREAD

**Issue by jerry1970** [marklieberman/foxygestures#129]
Since there are problems on Ubuntu using the right button but also the middle button, maybe it's an idea to add an option to start a gesture with a key? So I can have Ctrl+Shift+left-click starting the gesture...

**Comment by marklieberman** [comment]
I don't want to do this as it defeats the point of mouse gestures if you have to use the keyboard. The Linux/OSX issues will be solved eventually and #109 will be merged soon.

**Comment by jerry1970** [comment]
You're right about it defeating the purpose a bit... It's great news to read the linux issues will be solved!
