### ISSUE TITLE
Add-on removed?

### ISSUE THREAD

**Issue by zsau** [marklieberman/foxygestures#130]
The [Foxy Gestures add-on page](https://addons.mozilla.org/en-US/firefox/addon/foxy-gestures/) currently says "This add-on has been removed by its author." Was that intentional?

**Comment by jdreesen** [comment]
It seems to work again.

**Comment by zsau** [comment]
What happened? And why is Foxy Gestures 1.0.13 on AMO but only 1.0.11 in this repo? I'm sure there's a reason, but it just seems a little sketchy.

**Comment by marklieberman** [comment]
Mozilla notified me of an XSS issue. I have patched it, but I'm waiting for people to auto-update before pushing the commit.
