### ISSUE TITLE
How to open addons manager through gestures?

### ISSUE THREAD

**Issue by YandLiu** [marklieberman/foxygestures#131]
I tried `window.open('about:addons');` but unfortunately it didn't work.
It said "Error: Access to 'about:addons' from script denied"
Is it caused by limitations of WebExtensions or just this extension?
Then I tried to mimic pressing "Ctrl+Shift+A" after I read #89 , but due to my low level of programming, I  didn't make any progress yet... Could anybody help me achieve this goal?

**Comment by marklieberman** [comment]
Unfortunately, this cannot be done with Web Extensions. See the documentation for [tabs.create](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create)
> For security reasons, in Firefox, this may not be a privileged URL. So passing any of the following URLs will fail:
> * privileged about: URLs (for example, about:config, about:addons, about:debugging)
