### ISSUE TITLE
CloseTab - screen flashes white

### ISSUE THREAD

**Issue by bossman22** [marklieberman/foxygestures#132]
When I close tab with default CloseTab gesture, screen (webpage) flashes white. This is especially visible when web pages in tabs has dark background. Closing the tab with the x button does not have such an effect.

**Comment by marklieberman** [comment]
This isn't something I can change. I'm just calling [browser.tabs.remove](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/remove) and Firefox does the rest. Consider filing a bug with Mozilla.
