### ISSUE TITLE
Could any of these gestures be implemented?

### ISSUE THREAD

**Issue by memiarz** [marklieberman/foxygestures#133]
I'm using Firefox, and I'm having a hard time when these gestures are not around:

1. Go to First Tab ( Ctr + 1)
2. Go to Last Tab (Ctrl + 9)
3. Return to Previous Selected Tab (sooo helpful)
4. Add Bookmark (Ctrl + D)
5. Open Bookmark Manager/Library window (Ctrl + Shift + B)
6. Copy URL 

Can Firefox Quantum and FoxyGestures handle it?

**Comment by marklieberman** [comment]
1, 2: Yes
3: Probably
4: [Probably](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks/create)
5: As far as I know this isn't possible.
6: See #97

**Comment by memiarz** [comment]
Thank you. Let's hope that your addon will get some of these gestures in the future ;) Have a good day.

**Comment by rompec** [comment]
Hi, what about "Search for Selection with..." (opens popup listing all installed search engines and we can search for selection with the selected engine. )? I love this one!
Thank you

**Comment by memiarz** [comment]
@rompec you can use "Selected Text Searcher" or " Drag&Drop Zones" addons for that.

**Comment by rompec** [comment]
@memiarz thanks, I believe it's always better using as  few addons as possible and I guess foxygestures could offer this functionality somehow. I am finding that I cannot live without it :-)
