### ISSUE TITLE
Can't set URLs as 'file:///C:/Users/Me/Documents/startup.html'

### ISSUE THREAD

**Issue by foxy57** [marklieberman/foxygestures#135]
I have always used a locally-stored HTML file as the default home page for all of my browsers.

Foxy Gestures Options -> More Preferences:
Default URL for New Tab, New Window, New Private Window does not honor a file URI scheme such as: `file:///C:/Users/Me/Documents/startup.html`

I also created a custom "Goto Homepage" script as follows:
```
executeInBackground(() => {
   getActiveTab(tab => browser.tabs.update(tab.id, { url: 'file:///C:/Users/Me/Documents/startup.html' }));
});
```
And this fails to function as well.

Is this a limitation of the Web-Extensions or is this a foxygestures bug?

**Comment by marklieberman** [comment]
[That's a web extensions limitation.](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create)
