### ISSUE TITLE
Reopen a closed tab

### ISSUE THREAD

**Issue by TanHil** [marklieberman/foxygestures#137]
Is there an easy way to "create" this feature? Unfortunately my coding experiences are quite low :(...
I desperately miss a gesture like this.

Greets from Germany
Tanja

**Comment by mikamiel** [comment]
It is already implemented:
Foxy Gestures Options > Built-in Commands > Undo Close

**Comment by TanHil** [comment]
Ah! Haven't seen that!
Thanks

2017-11-18 13:26 GMT+01:00 mikamiel <notifications@github.com>:
