### ISSUE TITLE
Wheel gestures

### ISSUE THREAD

**Issue by bogoman** [marklieberman/foxygestures#138]
Hey !
Wheel Gestures dont work with the right mouse button as "Gesture Button". The rest is great :-))

**Comment by mikamiel** [comment]
Are you on Linux/MacOs? On Windows it works for me. Not tested on other OSes yet.

**Comment by bogoman** [comment]
Yes, I'm running on Linux Mint 18.1, not tested it yet on Win 10. Shame on me...thnx

**Comment by bogoman** [comment]
Sorry...new on Github...

**Comment by marklieberman** [comment]
The addon description on AMO explains how right button is problematic on OSX/Linux, please read it again. A workaround is coming in #109 soon.
