### ISSUE TITLE
Suggestion: drawing gesture while holding down "alt"-key & left mouse button (for iOS users)

### ISSUE THREAD

**Issue by alexgyger** [marklieberman/foxygestures#142]
Hi,
I am one of those hoping to use Gestures on iOS, like it worked with FireGestures.
Since you pointed out the issue with the limitations of web extentions and of how the different OS trigger the context-menu, I was now trying to pin point another way how it could work for me and other users on iOS:

**What if the gestures would only trigger when holding down the "alt"-key AND the left mouse button?** 
This was the only solution that made sense. But you would have to implement the conditionnal option that "alt" must be down first to trigger the gestures.

Other possibilities I quickly thought through didn't make sense on iOS:
"crtl" AND left mouse button wouldn't work -> opens context menu.
"shift" AND left mouse button -> would select content while drawing
Only left mouse button -> can't mark and select text/content.

Thanks for your add-on, great work!

**Comment by marklieberman** [comment]
This is similar to #129. A workaround will be coming when #109 is published, and eventually Firefox itself will be patched.
