### ISSUE TITLE
toggle full screen ?

### ISSUE THREAD

**Issue by fuorigioco1981** [marklieberman/foxygestures#149]
is it possible for a gesture like this?like we had in firegestures?

**Comment by marklieberman** [comment]
This isn't a perfect solution because it doesn't remember the last state of the window (normal or maximized) but it might help until I can implement a built in command.

This user script will toggle between fullscreen and maximized. Replace "maximized" with "normal" if you prefer that. 

```js
executeInBackground(() => {
    browser.windows.getCurrent().then(win => {
        if (win.state === 'fullscreen') {
            browser.windows.update(win.id, { state: 'maximized' });
        } else {
            browser.windows.update(win.id, { state: 'fullscreen' });
        }
    })
})
```

**Comment by fuorigioco1981** [comment]
THATS IT!THANK YOU!
