### ISSUE TITLE
New Action: View page/frame source

### ISSUE THREAD

**Issue by ThiefMaster** [marklieberman/foxygestures#151]
Both actions were common in legacy gesture extensions. They are easy to implement with user scripts but it'd be nice to have them builtin.

These are the scripts I'm currently using to get this functionality:

```javascript
executeInBackground(url => {
    getActiveTab(tab => {
        browser.tabs.create({
            active: true,
            index: tab.index + 1,
            url: 'view-source:' + url
        });
    });
}, [data.context.frameUrl]);
```

and

```javascript
(() => {
    var segments = top.location.pathname.split('/');
    segments.pop();
    top.location.pathname = segments.join('/');
})();
```

**Comment by marklieberman** [comment]
I haven't tested it myself yet, but #123 has a simpler script for parent page.

**Comment by IMSoP** [comment]
I don't know if there's a better way that a WebExtension can trigger, but note that this implementation is *not* the same as the browser's own "View Source" feature, because it causes a reload with no POST data, which Firefox is generally very good at avoiding.
