### ISSUE TITLE
i18n for window.confirm & window.alert

### ISSUE THREAD

**Issue by yfdyh000** [marklieberman/foxygestures#153]
https://github.com/marklieberman/foxygestures/search?utf8=%E2%9C%93&q=confirm&type=
https://github.com/marklieberman/foxygestures/search?utf8=%E2%9C%93&q=window.alert&type=
https://github.com/marklieberman/foxygestures/blob/701c7fc0b018fed4f77e148d2d00d2002a1063da/src/options/options.tab.backup.js#L129
.....

Also, I did not see the i18n extractor you used, it was not pushed?

**Comment by marklieberman** [comment]
I didn't use an i18n extractor because I didn't know about them. I don't see any mentions on MDN or in the example projects linked from MDN. I'll add one to the build process. Do you have a preference for a particular 18n extractor tool?

**Comment by yfdyh000** [comment]
I mistakenly think that `i18n` is a property for something i18n extractor.
No, I don't know which solution is good. Just some FYI:
1. https://github.com/i18next/ng-i18next
2. https://github.com/biesbjerg/ngx-translate-extract
3. [Why ngx-translate exists if we already have built-in Angular2+ i18n ?](https://github.com/ngx-translate/core/issues/495)

**Comment by marklieberman** [comment]
I added all the strings I forgot to internationalize in https://github.com/marklieberman/foxygestures/commit/61665f615fecaecb893ea5910d6dcec0a71a1392 Please update your PR and I will merge. Thanks!
