### ISSUE TITLE
Linux right-click problems

### ISSUE THREAD

**Issue by kustodian** [marklieberman/foxygestures#156]
Using gestures on Linux with the right mouse button doesn't work correctly. When you right-click it first displays the context menu. Once the context menu is displayed, you can continue drawing the gesture, but it's awkward. Other mouse gesture extensions usually solve this with hiding the context menu, and showing it on double right-click.

**Comment by AGCaesar** [comment]
This is mentioned in the readme!
And now finally fixed in Firefox as well. Depending on your Distro, the fix will be backported.
https://bugzilla.mozilla.org/show_bug.cgi?id=1360278
