### ISSUE TITLE
Supress context menu on righ-button gesture

### ISSUE THREAD

**Issue by Karry** [marklieberman/foxygestures#157]
Hi. 

First, thank you for this plugin.

I am using right button to activate gesture, but when I start gesture, Firefox open default context menu. I have to press Escape key or click somewhere else to hide this context menu then... It would be great to suppress this menu by plugin - if it is possible. 

I am using FF 57.0 on Linux.

**Comment by marklieberman** [comment]
Please read the addon description on AMO. It is a known issue with Firefox that will be solved soon. See also #109.
