### ISSUE TITLE
New Action: Previous Tab

### ISSUE THREAD

**Issue by del6597** [marklieberman/foxygestures#158]
Should be identical to the "Next Tab" command, but goes to the tab on the left instead of on the right.

**Comment by marklieberman** [comment]
There is already a previous tab command.

**Comment by del6597** [comment]
My mistake. I had trouble finding it. Is it possible to position it next to the Next Tab gesture assignment then?

**Comment by marklieberman** [comment]
I'm going to add categories to group the gestures next version. For now they are sorted alphabetically.
