### ISSUE TITLE
Support gestures on about:blank

### ISSUE THREAD

**Issue by jingyu9575** [marklieberman/foxygestures#159]
I have set about:blank as the new tab since about:newtab is not scriptable, but this extension does not  currently work on it either.
It seems that changing the content scripts' match_about_blank to true can fix it. 

https://github.com/marklieberman/foxygestures/blob/b40dd9dcb5b0b3c34676bbb0c1dad7f6b1d421a7/src/manifest.json#L50-L53
https://github.com/marklieberman/foxygestures/blob/b40dd9dcb5b0b3c34676bbb0c1dad7f6b1d421a7/src/manifest.json#L61-L64

**Comment by marklieberman** [comment]
I had true in the past but it caused problems that broke gestures inside frames on normal sites. Simply switching it to true isn't the solution.

**Comment by jingyu9575** [comment]
Thanks for your prompt reply. I tried on pages with nested iframe or frameset but did not notice any problem (Nightly 2017-11-21). For now I switched it to true locally and will see if problems arises.

**Comment by marklieberman** [comment]
I will check again just in case internal Firefox things may have changed in the last couple months.

**Comment by marklieberman** [comment]
Seems like something has changed because match_about_blank used to break things on a site I used, but I'm not longer seeing an issue. I will re-enable it.
