### ISSUE TITLE
Middle mouse tab scroll

### ISSUE THREAD

**Issue by ZoharML** [marklieberman/foxygestures#160]
Could it be possible to put the mouse over the tabs and scroll them using the mouse wheel?
And thanks for your work!

Zohar

**Comment by marklieberman** [comment]
It's not possible to get mouse events from the tab strip anymore. You may wish to follow this bug which is about the issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1285812

**Comment by Borkason** [comment]
@marklieberman there is an option *toolkit.tabbox.switchByScrolling* and if enabled, does exactly that. Maybe FoxyGestures could add a setting that just enabled/disabled this? I don't think many people know of *toolkit.tabbox.switchByScrolling* and giving this more visibility would be a great addition to FoxyGestures.
