### ISSUE TITLE
Feature request - new command to bookmark current page

### ISSUE THREAD

**Issue by attmang** [marklieberman/foxygestures#162]
Would be nice to have...

Thanks.

**Comment by zoredache** [comment]
++1 on this request please.

It sure seems like it should be pretty straight forward.  The [Gesturefy](https://github.com/Robbendebiene/Gesturefy/blob/master/src/lib/actions.js#L5) plugin seems to have this, but it lacks other functionality.

Actually it would be nice if there were 3 separate options if possible.  Add a bookmark (but don't dup), remove a bookmark, and a simple toggle.

**Comment by marklieberman** [comment]
Done in 9129a9839747d36dc980176b58dfd9ff32a4ab2d
