### ISSUE TITLE
Mouse Chord pops up context menu

### ISSUE THREAD

**Issue by rodalpho** [marklieberman/foxygestures#164]
I have the R+L mouse chord set to close the current tab. This works fine (on windows only obviously), but then when I _release_ the RMB it pops up the context menu on the new tab. 

I saw another issue about transferring the current gesture to the new tab after closing the current one, and suspect that's the problem as Windows pops up the context menu on release. So my guess is the same fix is needed here, and since those fixes (focus last selected tab and making the close tab chord repeatable) are functionality I desire anyway, I'm all for it!

Other issues : https://github.com/marklieberman/foxygestures/issues/139 https://github.com/marklieberman/foxygestures/issues/144

**Comment by marklieberman** [comment]
This is fixed by #144 which is now published to AMO in 1.0.14.

**Comment by rodalpho** [comment]
True that R+L to close the tab now works properly and doesn't popup the context menu.

However, I also bind the L+R chord to re-open the last closed tab-- and that does popup the context menu. 

Testing on MacOS with FX58b5 and the contextmenu about:config flag set.
