### ISSUE TITLE
Gestures wrote on page

### ISSUE THREAD

**Issue by Garash2k** [marklieberman/foxygestures#166]
If I go to this page https://api.scryfall.com/cards/mp2/39?format=text text shows up telling me what gesture I'm doing. Minor bug that's probably fixable!

**Comment by marklieberman** [comment]
That page's content type is plaintext. The gesture you're seeing written into it is the normal status text, but because the page type is plaintext it isn't being styled with CSS. It just appears as an unstyled DIV at the end of the document.
