### ISSUE TITLE
Right Mouse Button on OS X opens context menu on mouse up (Firefox 58 beta)

### ISSUE THREAD

**Issue by SamLewis0602** [marklieberman/foxygestures#167]
Hi, I followed the issue with OS X/Linux opening the context menu on mouse down rather than mouse up, and was happy to see that the fix was incorporated into the latest Firefox 58 beta. I have enabled the `ui.context_menus.after_mouseup` option in about:config but the context menu still seems to pop up after completing a gesture, which then cancels the gesture and I have to draw it again. It seems to be a 50/50 shot of whether the gesture will work or the context menu will pop up. Maybe it has something to do with the event not getting caught and cancelled, I'm not sure. I'm available to help you test if you need it.

**Comment by SamLewis0602** [comment]
Something I just noticed: it seems that the context menu pops up when I draw the gesture and release right click very quickly. If I go through the process a tad bit slower then it seems to register the gesture every time and doesn't show the context menu. Not sure if this is just a limitation of gestures in Firefox/OS X as I just switched to Firefox from Chrome when quantum was released.

**Comment by rodalpho** [comment]
I agree-- intermittently, maybe 20% of the time, gestures fail on MacOS and the context menu pops up after the gesture. It's unclear what causes this, but it's annoying enough that I wouldn't switch back to Fx as my primary browser.

**Comment by SamLewis0602** [comment]
@rodalpho just FYI, I switched to Gesturefy and it works perfectly, haven't had the context menu pop up once.

**Comment by rodalpho** [comment]
Yes, I switched back to Gesturefy also. I can't deal with making slow/deliberate gestures... I've been using mouse gestures for 15+ years now, they're in muscle memory.

**Comment by marklieberman** [comment]
I think this is caused by #180.
