### ISSUE TITLE
Add support for rocker gestures

### ISSUE THREAD

**Issue by marklieberman** [marklieberman/foxygestures#17]
It has come up a few times in reviews and other places

**Comment by natefitzgerald** [comment]
Just wanted to add a vote for this. Rocker gestures were the reason I used Firegestures to start with.

**Comment by marklieberman** [comment]
@natefitzgerald I expect to implement rocker/chording gestures for the next release. I'll update this issue in the coming weeks.

**Comment by marklieberman** [comment]
I need to rush 1.0.8 out before FF 56 goes to release at the end of the month due to #51. I've already done a bunch of work on getting chord gestures working, but I will have to bump the feature to 1.0.9.

**Comment by marklieberman** [comment]
There is a 1.0.9beta1 build in the beta channel on AMO with chord gesture support. If anyone interested could try it out, I'd appreciate it.
