### ISSUE TITLE
Scroll Up/Down ToTop/ToBottom the Selected Element

### ISSUE THREAD

**Issue by alainbryden** [marklieberman/foxygestures#171]
Many sites (gmail) put all their scroll-able content in a frame or scrollable div, rather than making the (document / window?) taller. Scroll to top/bottom doesn't work on these pages.

I used to use Fire Gestures, and its scroll-to-top/bottom gesture appears to have taken effect on whatever frame I right clicked, rather than just on the parent window.

Aside from submitting this as a feature request, is there a user script I can use in the mean time that will have the desired effect?

**Comment by alainbryden** [comment]
Managed to get this going with these (probably ugly) scripts. Feel free to adopt it into some sort of configurable feature.

**Scroll To Top (easy)**
```javascript
let node = mouseDown.target;
scrollNodeOrParentToTop(node);
function scrollNodeOrParentToTop(node) {
  if (node == null) { return null; }
  // If this element is scrollable, and it's scroll position isn't currently the top...
  if (node.scrollHeight > node.clientHeight && node.scrollTop != 0) {
    node.scrollTo(0, 0);
    return node;
  }
  // Otherwise, try scrolling its parent.
  return scrollNodeOrParentToTop(node.parentNode);
}
```

**Scroll To Bottom (harder)**
```javascript
let node = mouseDown.target;
scrollNodeOrParentToBottom(node);
function scrollNodeOrParentToBottom(node) {
  if (node == null) { return null; }
  // If this element is scrollable, and it's scroll position isn't currently the bottom...
  if (node.scrollHeight > node.clientHeight && node.scrollHeight - node.scrollTop != node.clientHeight) {
    // If this node is already quite close to being scrolled to the bottom,
    // try scrolling it the rest of the way, but also continue to its parent.
    // This helps *propagate* the scroll in case some elements can't be scrolled all the way down.
    var isCloseToBottom = node.scrollHeight - node.scrollTop < node.clientHeight + 20;
    if(!isCloseToBottom) {
        console.log('ended with ' + node + ' ' + node.scrollHeight + ' ' + node.scrollTop + ' ' + node.clientHeight + ' ');
        node.scrollTo(0, node.scrollHeight);
        return node;
    }
    node.scrollTo(0, node.scrollHeight);
    console.log('Continued after ' + node + ' ' + node.scrollHeight + ' ' + node.scrollTop + ' ' + node.clientHeight + ' ' );
  }
  // Otherwise, try scrolling its parent.
  return scrollNodeOrParentToBottom(node.parentNode);
}
```

Thanks for writing such an easily extensible add-on!

**Comment by alainbryden** [comment]
I see now there's a BubbleScroll method that's already meant to do something similar. 
https://github.com/marklieberman/foxygestures/blob/master/src/content/commands.js#L192

Would anyone object to a PR that changes the existing behaviour to the one above?

**Comment by marklieberman** [comment]
@alainbryden That bubble scroll implementation was used for bubbling up from non-scrollable iframes, as opposed to your implementation the bubbles up from DOM nodes. Anyway, the bubbleScroll function is broken since 1.0.13. What I need to do is use a combination of my fixed bubble scroll and your method to handle scrolling in a more general case.

**Comment by Fanolian** [comment]
I cannot scroll to top/bottom in BMO ([test link](https://bugzilla.mozilla.org/show_bug.cgi?id=1445537)). Is it the same issue? Thanks.
