### ISSUE TITLE
[Bug] 'Save Media As' action loses file extension after renaming a file

### ISSUE THREAD

**Issue by Faberman** [marklieberman/foxygestures#173]
Steps to reproduce:

1. Install Firefox 57+;
2. Install Foxy Gestures. Assign the gesture to 'Save Media As' action;
3. Perform the gesture on any image to save it. Image will be saved with extension.
4. Perform the gesture on any image, rename it, then save it. Image will be saved without an extension.
---
Windows 7 SP1 x64
Firefox 58.0b6 x64
Foxy Gestures 1.0.13

**Comment by marklieberman** [comment]
Everything after the Save As... dialog appears is handled by Firefox. I'm just calling `downloads.download({ url: '...', saveAs: true })` and Firefox does the rest. There's nothing I can do to affect the filename or know the name after you change it. You should file a bug with Mozilla.

**Comment by Faberman** [comment]
@marklieberman, try to save an image with and without renaming it using "Save image as" context menu command. Both will be saved with extension as expected. So, I think this is not a Firefox bug.

**Comment by marklieberman** [comment]
@Faberman The "save image as" command is not using "downloads.download()" internally so they are not comparable. Again, I have to ability to know or alter the filename after calling the downloads WE API. Once the "Save As..." dialog appears the entire download process proceeds without ever going back to Foxy Gestures code.

**Comment by Faberman** [comment]
Got it, thanks. I'll report a new bug on Bugzilla then.
