### ISSUE TITLE
Actions 'Open Link in a New <...> Tab' don't work

### ISSUE THREAD

**Issue by smithadat** [marklieberman/foxygestures#175]
They worked in a FireGestures, but not in a FoxyGestures. Just nothing happens when I make a gesture from a link. I tried to assign different gestures to the actions - doesn't help.

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0
Linux 4.12.14-041214-generic

**Comment by AlexanderKot** [comment]
I have the same problem
It seems stop opening new tabs after update to 1.0.14, at the same time in custom scripts stops functioning next script:

if (data.element.linkHref) { 
    data.element.linkHref = "https://docs.google.com/viewer?url=" + data.element.linkHref
    executeInBackground(data => commandOpenLinkInNewForegroundTab(data), [ data ]); 
} else { 
    executeInBackground(data => commandNewTab(data), [ data ]); 
} 

Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by marklieberman** [comment]
You guys are still on FF56. Support for "openerTabId" on the tabs.create() API was only added in FF57.

**Comment by smithadat** [comment]
Oh, ok. Thank you.

**Comment by AlexanderKot** [comment]
My script have been working before upgrade to 1.0.14, and now stops
What happens?

**Comment by marklieberman** [comment]
@AlexanderKot Call to tab.create()  in the commandXXXNewTab functions are now passing openerTabId. See #114.

**Comment by marklieberman** [comment]
I'm closing this issue because if you're on FF56 you should be able to continue using FireGestures which is superior to Foxy Gestures, and if not you're on FF57+ that supports openerTabId.
