### ISSUE TITLE
Is it possible to support '<link rel="next" ...>' navigation?

### ISSUE THREAD

**Issue by weiyucsie** [marklieberman/foxygestures#176]
[let list = document.querySelectorAll(next ? 'a[rel~=next]' : 'a[rel~=prev]');](https://github.com/marklieberman/foxygestures/blob/05c5d80a30aa179bc3495df68cf5b3c488831d96/src/content/commands.js#L142)
detects a[rel~=next] to follow the link
I wonder if it is possible to support link[rel=next]?
(ex. link[rel~=next],a[rel~=next] )

**Comment by marklieberman** [comment]
Page Up and Page Down commands follow rel=next. (See also More Options to turn that feature on or off.) I'm going to rename Page Up and Page Down commands next version because there is a lot of confusion with Scroll Up and Scroll Down commands.
