### ISSUE TITLE
gestures ignored when mouse is moving at the end of a gesture

### ISSUE THREAD

**Issue by michaeldstenner** [marklieberman/foxygestures#179]
I'm using firefox 57 on OSX (thanks for the workaround!), and running into the following issue:

When I start a gesture, stop, and THEN release the mouse button, everything seems to work fine.  However, if I just release the button WHILE moving, the gesture is ignored.  Apparently, this has been my habit for the last several years.  I never thought about it until it stopped working.  There is a substantial speed difference between these two, even if you do not count the fact that I never remember the first time :)

Again, thanks for a great add-on!

**Comment by marklieberman** [comment]
Underlying cause seems to be #180.
