### ISSUE TITLE
[Regression] Gestures broken with link beneath starting point

### ISSUE THREAD

**Issue by jrappen** [marklieberman/foxygestures#182]
Using gestures with a link beneath the starting point was previously possible.

---

* FoxyGestures: `v1.0.15`
* tested with browsers:
  * Firefox `v57`
  * Waterfox `v56`
* Win10 Pro x64 Version 1709
* Surface Pro 4 i7 with HighDPI

**Comment by marklieberman** [comment]
It's still possible. Nothing in that regard has changed. What was the last good version for you? Other users have reported issues with the Surface in the past.

**Comment by jrappen** [comment]
Firefox is fine again. Maybe a conflict with Ghostery or NoScript? They both updated in the meantime.

---

Waterfox is still broken. I know for sure that `v1.0.10` worked for me on Waterfox. Not sure about the versions in between.

**Comment by marklieberman** [comment]
Closing as you are reporting that Firefox is working.
