### ISSUE TITLE
Feature request: Enhance "back" to close tab...

### ISSUE THREAD

**Issue by stackrat** [marklieberman/foxygestures#184]
Would like to have the ability, either built-in or through a user-script, for the "back" gesture to close the current tab if executed when the beginning of navigation has been reached.

"Basic"ally...
If [can't go back] then 
     [close tab]
else
     [back]
end if

Thanks in advance.

**Comment by kafene** [comment]
This is a little convoluted but FoxyGestures doesn't have the `history` permission so I think it's the best I can do

```js
window.history.back();
setTimeout(function () {
    executeInBackground(() => {
        getActiveTab(tab => browser.tabs.remove(tab.id));
    });
}, 100);
```

**Comment by stackrat** [comment]
That works!

Thank you!!!
