### ISSUE TITLE
Feature request: add "previous tab" to list of chord gestures

### ISSUE THREAD

**Issue by doctorbass00** [marklieberman/foxygestures#185]
With chord gestures it is possible to navigate to next tab, but not to previous tab.

I love being able to left+right click to go to the next tab, and right+left click to previous tab. Would be awesome to see it implemented (and hopefully it would be pretty straightforward to do)!

Thanks :)

**Comment by marklieberman** [comment]
Scroll down, the list is alphabetical.

**Comment by doctorbass00** [comment]
Sorry, that was very noob, I didn't even see the scroll bar.
