### ISSUE TITLE
Request: 'Close tab, activate left tab' command

### ISSUE THREAD

**Issue by fwther** [marklieberman/foxygestures#188]
In FireGestures this was possible with a user script. Might be in Foxy too but I can't figure out how. Any help would be greatly appreciated, thanks !

**Comment by GiftWolf** [comment]
I think the next version will have the "activateTabThenClose" command which will make it easier to do.

**Comment by marklieberman** [comment]
Next version will have a setting to chose the active tab after Close Tab command. Let me know if this doesn't cover your use case.

![image](https://user-images.githubusercontent.com/6473247/34969013-a92e1c02-fa3a-11e7-9cfa-39627a562c95.png)

**Comment by fwther** [comment]
That's great! I would really like this as a separate gesture from the normal Close Tab command though. How would I specify which tab to focus with a user script? If possible. Tried working it out myself, but I'm (frankly) too much of a dummy to figure it out ;)

**Comment by GiftWolf** [comment]
try
```javascript
executeInBackground(data => {
    browser.tabs.query({ currentWindow: true }).then(tabs => {
        activateTabThenClose(data, tabs, 'left');
    });
}, [ data ]);
```

**Comment by vierlex** [comment]
Oh gosh thank you so much.
Thats a killer gesture for me and I am really happy to see User Scripts being available in Foxy Gestures AND finding this little snippet at the same time (I just wanted to implement it myself but have no clue about the API..).

So many <3 to you. (and to fwther too for referencing from that other issue where I came from)
