### ISSUE TITLE
Not working on touch devices in Quantum

### ISSUE THREAD

**Issue by Schmaiffe** [marklieberman/foxygestures#189]
I think this might be the same issue as the person with a Surface had. I have a different tablet PC (running Windows 10) which has both touch and a Wacom stylus. I have it set so that long press with the finger is right click, and there is no right click with the stylus. This is the behavior I'm getting:

When set to right click:
Touch: doesn't work, tries to scroll, selects text
Pen: n/a

When set to left click:
Touch: still doesn't work, tries to scroll and select text
Pen: works.

Interestingly, this only happens in Firefox Quantum. When I tried it in the Firefox fork Basilisk (which allows web extensions, so the same version was installed) it functioned as expected.

The other mouse gestures addon, Gesturify, has the same problem on Quantum.

I hope some of this is useful!

**Comment by marklieberman** [comment]
Since you are saying that Gesturefy is also bugged, I suspect that touch* event rather than mouse* events are being fired. However, I don't have touch hardware to debug on at the moment.

**Comment by marklieberman** [comment]
See #127
