### ISSUE TITLE
L+R chord: "Previous Tab" over link changes mouse cursor when returning to tab

### ISSUE THREAD

**Issue by GiftWolf** [marklieberman/foxygestures#193]
When I execute the L+R: "Previous Tab" chord gesture over a Link the tab is switched correctly. But when I switch back to the tab where the gesture started and move the mouse inside the page area the cursor changes for a short duration of time to the finger symbol and then to the "no drag" (I don't know the correct name) symbol. Then it returns to normal.

**Comment by marklieberman** [comment]
I'm not able to reproduce this. I'm starting on a link and doing the chord L+R which goes to the previous tab. Then I've tried R+L next tab and just clicking back to the original tab, but I don't see the no-drag cursor.

**Comment by GiftWolf** [comment]
I return to the original tab by clicking the tab in the tab bar on top of the address bar. Then move the mouse down into the website area below the address bar. When entering the page area the cursor changes for a split second. Here is a video, however only switching to the finger cursor is visible.
![ezgif-4-590658a472](https://user-images.githubusercontent.com/992940/34868680-e2c85080-f784-11e7-9b7c-e1e67f08d03c.gif)


There is another bug visible in the video: When switching to the left tab, the cursor keeps being the finger although there is no link under it.

**Comment by marklieberman** [comment]
I can't think of a solid way to fix this issue. There are no APIs to directly manipulate the cursor icon. It seems like Firefox should be the one resetting the cursor when the active tab changes.
