### ISSUE TITLE
How to restore default settings / gestures?

### ISSUE THREAD

**Issue by tmaenner** [marklieberman/foxygestures#197]
Hi,
somehow I've lost the default settings / gestures...
Even re-installing didn't help.
Is there a script file I could use to restore the settings?

Cheers,
Tom

**Comment by marklieberman** [comment]
I've implemented a reset button for the next version of Foxy Gestures. Until that is released, you can create a new Firefox profile and just install FG, export the settings, and then restore those settings to your original profile.

**Comment by tmaenner** [comment]
Thanks Mark for the work-around suggestion, it worked!!!

Cheers,
Tom
