### ISSUE TITLE
Request for several gestures

### ISSUE THREAD

**Issue by Nenooo** [marklieberman/foxygestures#199]
Love this addon. Exactly what i was looking for. But i would appreciate some more gestures:
- close the current window
- close firefox
- goto the first tab
- goto the last tab

Great work so far :)

**Comment by marklieberman** [comment]
1 and 2 can be done easily. 3 and 4 have been implemented and will be in the next version.

**Comment by marklieberman** [comment]
I've implemented all except "Close Firefox". A WebExtension API does not appear to exist that gracefully exits Firefox.
