### ISSUE TITLE
Can it work inside other window types?

### ISSUE THREAD

**Issue by HallyM** [marklieberman/foxygestures#202]
FireGestures worked in window types like about:addons, individual addon settings page or about:preferences.
Can FoxyGestures do that too? It's really annoying to get accustomed to gestures but then find out that they don't work inside certain window types.
Thank you.

**Comment by jdreesen** [comment]
Please read https://github.com/marklieberman/foxygestures#limitations

**Comment by HallyM** [comment]
That's nasty :( . Thanks for the quick reply.
