### ISSUE TITLE
Left gesture button problems - left button is sticked

### ISSUE THREAD

**Issue by KreativaAltius** [marklieberman/foxygestures#204]
Hi, I use left mouse button for the gestures.
There are problems for instance, when I use the image editor on pagesites. If I want to scale the image then the "button" sticks to image when I release the left button - it is so, as if I din't release the button at all.

This happens also on rearranging the windows on some pages. - The left button stays sticked.

Otherwise the addon it really great, but this is really irritating.
Regards

**Comment by marklieberman** [comment]
If you share some links I can test then I will look into it. However, it is not unexpected because with web extensions I am handling the same mouse events that the page is using. So, the page can interfere with the mouse events, prevent handling, etc.

**Comment by marklieberman** [comment]
Closing for no response.
