### ISSUE TITLE
Hybrid Close Tab / Close Window

### ISSUE THREAD

**Issue by mike-mo** [marklieberman/foxygestures#205]
As a FireGestures transplant, I'm looking at the [Supported Commands vs. FireGestures](https://github.com/marklieberman/foxygestures/wiki/Supported-Commands-vs.-FireGestures) page, which lists "Close Tab / Close Window" as "Implemented (Close Tab)".

The problem I'm facing is that when I execute a close tab gesture on my last tab, instead of having the window close, my current tab is replaced with a blank tab / new tab page. Is this expected?

**Comment by marklieberman** [comment]
What is the value of `browser.tabs.closeWindowWithLastTab` in about:config? When I close the last tab in a window it closes the window.

**Comment by mike-mo** [comment]
Yep, changing that to its default does fix my issue. I wonder where its value of `false` came from...

Oh well, maybe changing it won't affect any other scenario for me. Thanks for the fix!
