### ISSUE TITLE
Does gesture in about:blank really work?

### ISSUE THREAD

**Issue by ashleylai87** [marklieberman/foxygestures#207]
As per changelog in Version 1.1.0 _Re-enabled support for gestures on about:blank_, I was estatic to see gesture finally will work again. However I can't seem to get it working. I am using the following userscript : 

![userscript](https://user-images.githubusercontent.com/35674888/35202984-bfc52f02-ff60-11e7-9868-b5ff7bfad6c7.PNG)

and setting up about:blank at 'More preferences'

![about blank](https://user-images.githubusercontent.com/35674888/35203008-da924644-ff60-11e7-9469-579a57feacfe.PNG)

Next, I load up google.com and using right click gesture up on blank space to open new tab. The new tab is opened, however mouse gesture doesn't seem to work at the newly opened tab.
Did I do anything wrong?

Note: Using firefox nightly and beta for two PCs respectively, gesture on new tab (about:blank) don't work either.

**Comment by rodalpho** [comment]
About:blank does work for me, gestures function there. About:home does not work with the default homepage.

**Comment by ashleylai87** [comment]
rodalpho, now that is weird. It don't work for both of my firefox installation.

Hmm.......question, does your firefox preferences below set to false?

browser.newtabpage.activity-stream.aboutHome.enabled
browser.newtabpage.activity-stream.enabled
browser.newtabpage.activity-stream.prerender
browser.newtabpage.enabled
browser.newtabpage.enhanced

**Comment by rodalpho** [comment]
All the above are set to true except browser.newtabpage.enhanced which I set to false.

I ended up building my own startpage based on the very simple skeleton linked below, but gestures on about:blank did work.

https://github.com/katalysatorn/MSEdge-StartPage

**Comment by rodalpho** [comment]
Sorry, no clue. Maybe it only works on MacOS? I haven't tested in windows yet.

**Comment by marklieberman** [comment]
@ashleylai87 The all_frames:false property on line 67 is correct. There is one set of scripts for all frames, and additional scripts for only the top level frame. About:blank is a top level frame so both sets of script should be injected into it. Anyway, it was working for me on FF developer edition. I'll check again on stable as soon as my install receives the update.

**Comment by ashleylai87** [comment]
rodalpho, I see......MacOS, then again, I am using Windows 7 and 10. (Nightly on 7 and beta on 10)

marklieberman, so there is no issue with line 67? 
Hmm......, I thought it might be caused by umatrix and ublock origins, but disabling them don't change anything either.

There is another strange issue with private tab too. (which I think should be normal? Or maybe not...cause when one types about:blank and press in private windows, it tends to go white blank screen instead of pure purple)
Here a 1 minute video at 15fps in zip file to demonstrate both issues with gesture not functioning in about:blank. (Github doesn't allow direct mp4 upload, so I simply zipped it instead)
[foxygesture.zip](https://github.com/marklieberman/foxygestures/files/1654345/foxygesture.zip)

**Comment by marklieberman** [comment]
@ashleylai87 I think it might be a Firefox issue...

When I create new about:blank tabs in a private window, sometimes they are a blank white page, and sometimes they are a blank purple page. If the page is white, gestures work. If the page is purple, they do not work. There doesn't seem to be a pattern if the tab is white or purple, its just some unknown race condition inside Firefox.

Normal non-private windows are always producing blank white pages, and gestures are working there.

**Comment by ashleylai87** [comment]
@marklieberman , but in the same video, the gesture doesn't work in about:blank (non private windows) too.

I sincerely doubt it is firefox issue.
Reason, if I use https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/ and set about:blank with that add-on, foxygesture works?

Another video to demonstrate:
[foxygesture + new tab override.zip](https://github.com/marklieberman/foxygestures/files/1654958/foxygesture.new.tab.override.zip)

What is the difference between foxygesture 'Default URL for tabs opened with New Tab command' and newtaboveride settings when about:blank is specified?

**Comment by marklieberman** [comment]
Gestures are working in non-private about:blank tabs. I have two users reporting that it works, as well as my own tests.

In your first video, your blank tabs that you open with a gesture are purple. Gestures are not working in those purple tabs, and I do not know why they are purple. about:blank tabs should be white, like in empty iframes. I still think these empty purple tabs are a Firefox bug. In your second video I can see the blank tabs flash purple before they turn white. That's probably something to do with how the newtaboverride addon works.

> What is the difference between foxygesture 'Default URL for tabs opened with New Tab command' and newtaboveride settings when about:blank is specified?

FG new tab URL is just the URL passed to browser.tabs.create() when you do the related gesture. newtaboverride addon is most likely setting [chrome_url_override](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/chrome_url_overrides).

**Comment by ashleylai87** [comment]
If that the case....I have no idea what goes wrong with both of my firefox installation. Oh well, can't do much about it if it is firefox issue.

The only difference between grey and pure white about:blank when using firefox inspector:

Pure white
<html><head></head><body></body></html>

Grey
<html><head></head></html>

Only body part is missing. Feel free to close this issue. I give up.

**Comment by marklieberman** [comment]
Seems like there has recently been a number of changes which were trying to minimize the white flashes when loading tabs. (For dark theme users.) I wouldn't be surprised if this issue was related. https://bugzilla.mozilla.org/show_bug.cgi?id=1379587

**Comment by ashleylai87** [comment]
Probably it is as you said.
I am using Light theme with Compact density. However, changing it back to Default theme and Normal density isn't working too.
Well, nothing to do until mozilla fixes all those "Depends on" bug lists. 
At least the issue isn't foxygesture fault.
Okay, I am closing the topic for good. Thank you @marklieberman
