### ISSUE TITLE
Cannot set file:// URL for new tab page

### ISSUE THREAD

**Issue by rodalpho** [marklieberman/foxygestures#210]
When I set a file:// URL for my new tab page and gesture to open a new tab, nothing happens. Is this a webextension restriction?

I just hosted it somewhere so not a huge deal, but if it's possible to use local file URLs, that would be convenient.

**Comment by marklieberman** [comment]
file: protocol is one of the forbidden protocols for web extensions APIs, so that will not work. Please see the url parameter in the [MDN documentation for tabs.create](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create).

**Comment by rodalpho** [comment]
That's what I figured. Webextensions are no fun at all.
