### ISSUE TITLE
Request: 'View page in no style' gesture action

### ISSUE THREAD

**Issue by siebenmann** [marklieberman/foxygestures#212]
Switching badly designed pages into being viewed in no style (View -> Page Style -> No Style) and then sometimes switching them back is such a routine thing for me that in FireGestures, I made a user script to do this (the FireGestures JavaScript code required is tiny). Unsurprisingly, my user script JS doesn't work in Foxy Gestures in Firefox 57+. Would it be possible to implement this in Foxy Gestures? My preferred version would be as a toggle; invoke once to switch to no style, invoke again to switch back to the regular style.

(Alternately, if it's still relatively simple JS I can do it as a user script, but sadly I don't know enough about the WebExtensions programming environment to research and write it on my own.)

**Comment by marklieberman** [comment]
Unfortunately, there is no web extension method to toggle that setting so it cannot be done even with a user script. It is an internal function of Firefox.

There are some hackish workarounds that won't perfectly replicate the "No Style" function. You can read about it in this stackoverflow post: https://superuser.com/questions/447269/is-there-any-way-to-view-a-webpage-without-styles-in-chrome

**Comment by marklieberman** [comment]
Closing this issue because it requires Firefox to implement support for toggling No Style attribute on tabs. I suggest filing a feature on BugZilla to add it to the tabs APIs.
