### ISSUE TITLE
Permissions page out of date

### ISSUE THREAD

**Issue by fritzophrenic** [marklieberman/foxygestures#214]
Today I got notified of a new FoxyGestures version and asked to approve new permissions. I checked the [permissions page](https://github.com/marklieberman/foxygestures/wiki/Why-Permissions-Are-Required) on the wiki for why these permissions are needed, but found nothing:

- Read and modify bookmarks
- Read and modify browser settings

Please update the wiki page.

**Comment by marklieberman** [comment]
Wiki has been updated.
