### ISSUE TITLE
New command: Back or Close

### ISSUE THREAD

**Issue by phts** [marklieberman/foxygestures#216]
Please add a new command "Back or Close". This would behave like "History back" and if there is no more history then it closes the tab.

I tried to add an user script:

```
if (document.referrer == "") {
    window.close()
} else {
    history.back()
}
```

But it says that it cannot close tab due to security violations.

**Comment by c01o** [comment]
set `about:config` -> `dom.allow_scripts_to_close_windows` `True` to get ` window.close()` work.

**Comment by stackrat** [comment]
Setting dom.allow_scripts_to_close_windows to True did not get the OPs script to work for me

This works most of the time for me...
https://github.com/marklieberman/foxygestures/issues/184
I bumped the timeout to 200ms which improved accuracy with no noticeable side effects.

**Comment by c01o** [comment]
@stackrat 
great, this seems roughly what foxygestures did on default command `DR`.
https://github.com/marklieberman/foxygestures/blob/1786d63de739a2b8f4ee0cf5d9d40c25ed684eb7/src/background/commands.js#L664-L693

**Comment by stackrat** [comment]
@c01o 
Credit goes to Kafene.  I'm just another user who had the same issue as @phts
