### ISSUE TITLE
Ideas for better communication when new permissions are added?

### ISSUE THREAD

**Issue by asahiko** [marklieberman/foxygestures#219]
With the latest release requiring bookmark access, [several people are leaving one-star review on the add-on site](https://addons.mozilla.org/en-US/firefox/addon/foxy-gestures/reviews/?src=api). Although I never understand people who think that this an evil worthy of a one-star, it is a phenomenon worth addressing to avoid unnecessary user anxiety and undeserved dip in the add-on rating.

Users already have agreed to plenty of permissions when installing the add-on, but forget about it once they start using it, and hence might get anxious when the add-on asks for further permissions upon an update. The reasons for the requirement are sufficiently outlined at [the wiki page](https://github.com/marklieberman/foxygestures/wiki/Why-Permissions-Are-Required), but the link is buried lower in the add-on site description. Also, the same description appears in about:addons, but the description there is turned into plain text and the link is not clickable there. 

Edit: link

**Comment by marklieberman** [comment]
Pay no attention to AMO reviews. I stopped caring when it became apparent that people who complain the loudest usually haven't read the description. I used to get 1-star reviews complaining about the context menu popup on OSX/Linux when the very first (and bold) line of the description explained it was an API limitation. Requiring all these permissions will always be an issue, because the entire purpose of FG is to automate as many features of the browser as possible using gestures. If you have any ideas on how to improve the situation I'm willing to hear them. I'm not very keen on ideas like opening a "changelog" tab on updates however, because it requires upkeep.

**Comment by rodalpho** [comment]
Changelog is not required (although it would certainly be appreciated). 

I personally do need a clear explanation of the need for each individual permission before I'll use an extension. 

Bit of background. The Chrome extensions store is full of malware, and most of it came up when the author of an awesome popular extension decided to sell it to a shady Russian or Chinese company. And then the updates keep coming for an extension you depend on, and used for years, except now you suddenly start seeing weird ads, or your browsing history is sent directly to Shenzen. People get paranoid about that stuff, and reasonably so.

**Comment by marklieberman** [comment]
There is a changelog on the README and in the AMO change notes. I meant I don't want to do an intrusive "here's whats new" popup/tab on every update.

**Comment by rodalpho** [comment]
Hopefully that makes it more visible! I knew you documented the permissions-- that's why I use the addon. Just wanted to explain why people were so paranoid about this stuff, it's because they've been burned before.

**Comment by asahiko** [comment]
One more idea for future releases (the next time FoxyGestures adds additional permissions) is to clarify the permission change along with the new feature item in the changelog. For instance, the latest changelog could have said something along the lines of:
> Added bookmark/unbookmark URL command. (This requires bookmark access permissions.)

Regarding the AMO description, I like that new placement. Hopefully more people will see it now. Thank you!
