### ISSUE TITLE
Optional Permissions

### ISSUE THREAD

**Issue by stoically** [marklieberman/foxygestures#225]
Since I saw some angry reviews about too many permissions upfront - maybe it would be worth looking into [optional_permissions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/optional_permissions)? Just a thought - feel free to close.

**Comment by marklieberman** [comment]
Great idea. I can just use permissions API to request the more controversial permissions like bookmarks when the commands are first used. Thanks.

**Comment by stoically** [comment]
Just a heads-up: There's still a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1435617) where it will ask for the permission once when you request them. And then once again if you update the Add-on - not again after that though. I guess I'm adding that to the MDN page as well.

Also, permissions.request "can only be made inside the handler for a user action", which can be a it tricky - but that's documented anyway.
