### ISSUE TITLE
Options page is blank

### ISSUE THREAD

**Issue by creideiki** [marklieberman/foxygestures#227]
Foxy gestures 1.1.0 on Firefox 58.0.2 (64-bit build) on Windows 7.

I've seen a lot of bugs where the options page is blank, but not one with this log output. Thus, here's yet another variation on a familiar theme!

I just upgraded Firefox on a Windows 7 VM from 56 to 58, to see if enough extensions have been ported by now to finally make it useable. I used [All-in-one gestures](https://addons.mozilla.org/en-GB/firefox/addon/all-in-one-gestures/) in 56, but that is abandoned, so I wanted to try Foxy gestures in 58. Unfortunately, the options page is blank and the JavaScript console just says `<unavailable>`:
<img width="719" alt="foxy-gestures-options-blank" src="https://user-images.githubusercontent.com/1296902/36355298-56b8f00c-14e1-11e8-9e79-ebfdcdf751c3.png">
If I try to use gestures on another web page, I get a purple gesture trail, but nothing I've tried have activated any browser command. Of course, since I can't see the options page, I have no idea what gestures to try.

**Comment by marklieberman** [comment]
This is an issue that happens on some installs that I believe is related to a bug in the Firefox sync engine. The thing that most often fixes it is restarting Firefox. See: #76.

**Comment by creideiki** [comment]
I had already restarted Firefox several times, but I tried again. After another five restarts I can suddenly see the options tab.

Also, I have never used Firefox sync.

**Comment by marklieberman** [comment]
I'm using the storage.sync API which is supposed to behave like old-fashioned local storage when you don't have a sync account.
