### ISSUE TITLE
Wheel Gestures Page Up/Down Missing

### ISSUE THREAD

**Issue by jesse9212** [marklieberman/foxygestures#229]
Page up and Page down missing from list of commands on:
Other Gestures ->Wheel Gestures -> Scroll Up / Down Dropdown options

Before FF57 this addon had the ability to hold right click and page down or up with one scroll wheel notch at a time.

**Comment by marklieberman** [comment]
There is  Scroll Up and Scroll Down command that can be assigned to wheel gestures. The amount of scrolling is configurable in More Preferences and defaults to 80% viewport height.

![image](https://user-images.githubusercontent.com/6473247/38391508-66a8a9dc-38f2-11e8-9c35-839804986be9.png)
