### ISSUE TITLE
Make gestures work on internal pages

### ISSUE THREAD

**Issue by zakius** [marklieberman/foxygestures#23]
And if not possible with current API bother Mozilla long enough to make it possible

EDIT: seems like gestures get disabled also on addons website, just like in chromium...
if I wanted to use chromium I'd just use chromium, right?

**Comment by marklieberman** [comment]
This is not possible in Web Extensions.

**Comment by zakius** [comment]
then extension is basically useless just like every single gestures extension for chromium
good job mozilla
