### ISSUE TITLE
Gesture tooltip/status bar item appears at bottom of page instead of bottom of window on certain pages

### ISSUE THREAD

**Issue by whjms** [marklieberman/foxygestures#230]
Version: 1.1.0
Firefox version: 60.0b4
OS: Debian Linux 9.0

Sample URL: https://gcc.gnu.org/onlinedocs/cpp/Macros.html (any of the links on https://gcc.gnu.org/onlinedocs/cpp/ seem to work)

I can't find anything strange about this site in particular that would cause the tooltip to appear in a different position. Can anyone else repro?

![screenshot_20180318_193612](https://user-images.githubusercontent.com/3392687/37572619-23bbb586-2ae4-11e8-9b94-a45dffd7f338.png)

**Comment by marklieberman** [comment]
That website has a CSP policy that is blocking the loading of inline `<style="...">` tags. So the status text is just getting appended to the end of the document as an unstyled div. When I try to edit the DOM in the inspector, I get:

```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src https://gcc.gnu.org http: https:”). Source: all: initial; display: block; position... Macros.html
```

**Comment by whjms** [comment]
Agh, that sucks. This class of issue is really one of my main sticking point with the transition to webextensions. Anyways, thank you for investigating!
