### ISSUE TITLE
Can't get userscripts working

### ISSUE THREAD

**Issue by Fuchsritter** [marklieberman/foxygestures#235]
Hello,

i try to get a userscript to open the sidebar. I get one from http://www.xuldev.org/firegestures/getscripts.php. But no script works.

Is there a trick?

**Comment by marklieberman** [comment]
Those are FireGestures user scripts. They are not compatible with Foxy Gestures. The two addons are built using completely different APIs which do not allow me to support existing user scripts. Please see the User Scripts article in the Git Wiki for information about writing user scripts in Foxy Gestures.
