### ISSUE TITLE
Mouse wheel changes to zoom after using gestures

### ISSUE THREAD

**Issue by seqtools** [marklieberman/foxygestures#236]
In Firefox, the mouse wheel changes from scroll lines to zoom the page after using gestures.
mousewheel.with_control.action = 0 does not help.

**Comment by marklieberman** [comment]
Since FG hasn't updated in a few months and suddenly I have several reports of this issue, I'm gonna go out on a limb here and say something in FF probably changed. Can you guys start posting details like OS, browser version, and other extensions you are using the can do zoom stuff?

**Comment by zhanglongqi** [comment]
Thanks for your reminding. It seems the problem of the addon: https://addons.mozilla.org/addon/zoom-page-we/
The problem did not show after I disable the zoom-page-we. I found one option of it called: `Enable mouse Right+Wheel to zoom in/out`.
The problem did not show after I unchecked the option and enabled the addon.

**Comment by marklieberman** [comment]
This was a conflict with the Zoom Page WE. Unfortunately, in Web Extensions we all share the same event scope so its possible for another extension to handle a mouse event and stop propagation before Foxy Gestures can process it.
