### ISSUE TITLE
Gestures don't work in PDF.js view

### ISSUE THREAD

**Issue by Speedy-Gonzalez** [marklieberman/foxygestures#242]
Hi,

I'm using the latest foxygestures with Firefox 60.

Gestures don't work in PDF.js tabs anymore. Maybe I'm wrong, but wasn't that possible in older releases of foxygestures or Firefox?

Thanks.

Best regards,
Speedy

**Comment by marklieberman** [comment]
No, it should never have been possible. PDF.js is a system addon and behaves like other moz-extension: URLs in that it doesn't get content script injections.

**Comment by marklieberman** [comment]
Just to correct my previous post, it seems gestures did work until a recent security issue with PDF.js was patched. See: #249 and the linked issues/BugZilla entries.
