### ISSUE TITLE
Optional permissions required

### ISSUE THREAD

**Issue by Guttts** [marklieberman/foxygestures#243]
I see some gestures have info that optional permission is required for downloads for example. Is it something user can solve? How? Havent found any info about this. Thanks

**Comment by marklieberman** [comment]
https://github.com/marklieberman/foxygestures/wiki/Why-Permissions-Are-Required

> Beginning with version 1.1.1 and Firefox 60, the following permissions are optional. They will only be requested if you assign a command that requires the permission. These permissions can be managed in the More Preferences tab.
