### ISSUE TITLE
Undo close stopped working

### ISSUE THREAD

**Issue by evgenetic** [marklieberman/foxygestures#244]
Hi, I'm running Firefox 60.0.1 and the "undo close tab" gesture stopped doing what it's supposed to do. The addon does recognize that the gesture is accepted and seemingly translates it into the assigned command in the lower left corner status text, but doesn't actually execute the command. Manually right clicking on the Firefox tab bar and selecting "undo close tab" does work as intended, just not the gesture.

Please look into it. 
Thanks.

**Comment by shinji2009** [comment]
i think save media now stop working also. moz60.* update bug?

**Comment by marklieberman** [comment]
@evgenetic If it starts working again when you start a new session, then its a bug in Firefox that I encountered in Nightly. 

@shinji2009 Make sure you have the 'downloads' optional permission in Options > More Preferences. I think Firefox may not actually retain required permissions when upgrading from 1.1.0 -> 1.1.1 with optional permissions.

**Comment by shinji2009** [comment]
**marklieberman**  yes it works thanks

**Comment by aspera7** [comment]
I tried opening a new session and the undo close remained inoperative.

**Comment by marklieberman** [comment]
I'm fairly sure this whole issue is internal to Firefox because the handful of times it occurred while I was testing it on Nightly, the exception always originated from the call to the sessions API.
