### ISSUE TITLE
Scroll to top/bottom fails to finish

### ISSUE THREAD

**Issue by TarAlcarin** [marklieberman/foxygestures#245]
This issue is apparently super-specific, but I'm able to consistently reproduce it on Windows 10, Firefox 60.0.1. (Chrome does not seem to be affected.)

**How to reproduce:**
1. Go to article on engadget.com (example: https://www.engadget.com/2018/05/22/belkins-3-5mm-to-lightning-cable-delivers-retro-connectivity/)
2. Click on "SHOW MORE COMMENTS ..." button below article
3. Invoke "scroll to top" or "scroll to bottom" action

**Expected behaviour:**
A smooth scrolling to top/bottom of page and then regaining control of the scrolling function.

**What happens:**
The page scrolls erratically towards top/bottom, but even after making it all the way, it keeps jumping slightly up and down forever. Mouse wheel scrolling does not work after this.
Only the tab with the engadget article is affected and the problem persists even after viewing another tab.

**Workaround:**
Refreshing the page or clicking a link in the page resolves the situation.

**Comment by marklieberman** [comment]
There is a postMessage infinite loop caused by a naughty script on that page echoing all messages. I have to investigate more to determine if it is possible to break the loop on FG side.
