### ISSUE TITLE
May be a bug...

### ISSUE THREAD

**Issue by ZeronoFreya** [marklieberman/foxygestures#250]
这是一个非常棒的插件!

与Zoom Page WE右键冲突
绘制手势之后，滚动鼠标滚轮会缩放页面，
这是Zoom Page WE的快捷键 （mouse Right+Wheel to zoom in/out）（默认），
禁用之后解决。
猜测是绘制手势之后鼠标右键的状态异常，但我不确定。

Google Translate:

This is a great plugin!

Conflict with [Zoom Page WE](https://addons.mozilla.org/zh-CN/firefox/addon/zoom-page-we/)
After drawing a gesture, scroll the mouse wheel to zoom the page.
This is a Zoom Page WE shortcut (mouse Right+Wheel to zoom in/out) (default).
Disable after resolution.
The guess is that the state of the right mouse button is abnormal after drawing a gesture, but I'm not sure.

**Comment by marklieberman** [comment]
known issue. disable wheel zoom setting in ZoomPage WE

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
