### ISSUE TITLE
Can't copy in User Scripts

### ISSUE THREAD

**Issue by zephyrer** [marklieberman/foxygestures#255]
For example, "Copy URL to Clipboard" in [List of Common User Scripts](https://github.com/marklieberman/foxygestures/wiki/List-of-Common-User-Scripts) fails and reports an error:

> document.execCommand(‘cut’/‘copy’) was denied because it was not called from inside a short running user-generated event handler.

From the article [Interact with the clipboard](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Interact_with_the_clipboard), it seems that the WebExtension needs to ask for the "clipboardWrite" permission.

Could it solve this problem?

**Comment by marklieberman** [comment]
User scripts are not called from user generated handlers so it won't work regardless. In my experience the clipboard works poorly in web extensions. See #143. I've heard that new APIs are coming for clipboard access in the coming year, so the situation may improve.
