### ISSUE TITLE
Logo proposal for FOXYGESTURES

### ISSUE THREAD

**Issue by ggabogarcia** [marklieberman/foxygestures#259]
Hello, I'm a graphic designer and I like to collaborate with open source projects. I would like to design a logo for your Project I will be happy to collaborate with you :)

**Comment by marklieberman** [comment]
If you're willing to contribute a free icon then I wont say no. It will definitely be better than the one I managed to scrape together,

**Comment by ggabogarcia** [comment]
Of course sir :)
