### ISSUE TITLE
Settings don't seem to be saved.

### ISSUE THREAD

**Issue by onodera-punpun** [marklieberman/foxygestures#26]
No idea what the cause is.. Or maybe I am missing some "save" button?

**Comment by marklieberman** [comment]
Settings should just apply as soon as you change them. Try uninstall in re-installing the plugin. You can also open the browser console (Ctrl+Shift+J on Windows) and look to see if there are any errors when you touch the Foxy Gestures settings.

**Comment by marklieberman** [comment]
I've just discovered that the step property on an input[number] doesn't just control the increment when you press up and down, but actually validates that the input falls on a step. (e.g.: min:0, max:6, step:2 -> only values:0,2,4,6 are valid.) This will cause the bad setting to reset to zero when you close the options because the value is invalid. Maybe this issue is what you encountered.

**Comment by asimon** [comment]
No setting is saved at all.  No checkbox, no selection, nothing.  In the console the following error appears when the page with the settings is opened:
`<unavailable> Possibly unhandled rejection: {}  angular.min.js:123`
The errors occurs again when entering a gesture under "Build-in commands".  Gestures are not saved either.

**Comment by marklieberman** [comment]
Something has changed in the Firefox internals because when saving settings Nightly is throwing
```
XrayWrapper denied access to property "load" (reason: value is callable)
```
followed by
```
Error: DataCloneError: The object could not be cloned.
Stack trace: ..
```
where the previous behavior either didn't care or just ignored callable properties. I will have to work around this new limitation somehow.

**Comment by marklieberman** [comment]
@onodera-punpun @asimon I've published a beta version to AMO that should fix the settings in Nightly. I'd appreciate if you guys can test it. Scroll down to the bottom of https://addons.mozilla.org/en-US/firefox/addon/foxy-gestures/.

**Comment by asimon** [comment]
Foxy Gestures 1.0.7beta fixes this issue, I can no longer reproduce it with Nightly. Thanks!
