### ISSUE TITLE
Gestures don't work while page is loading

### ISSUE THREAD

**Issue by Aelius51** [marklieberman/foxygestures#262]
There's a brief moment before a page is loaded when gestures don't work. I'm _not_ referring to the stage in which elements on the page are in the process of loading (particularly images); I'm referring to the stage before the web page even starts to get loaded in and everything just looks white. It's hard to explain, and I'm afraid I don't have enough technical knowledge to be more specific than that. You should be able to replicate this yourself if you know of a website that's currently offline.

This isn't just a problem with websites that are down, though. If you're very quick with your gestures (and I am _very_ quick,) sometimes you can start a gesture too soon after loading a new tab.  So, for example, if you gesture to open a new tab and then immediately try to gesture again, it will fail.

I searched all open issues _and_ closed issues but I did not see any mention of this problem. I suspect and fear that this is one of those "special" pages that WebExtensions doesn't let you touch (for... reasons. Presumably.)

**Comment by marklieberman** [comment]
This is written in the Limitations section of the readme and also paraphrased in the addon description on AMO:
> More importantly, the mouse gestures will not work until the document body of the website you are visiting has parsed. In other words, the DOM must be at least partially parsed but content does not have to be loaded. This limitation also applies to frames within the website. This is an inherent limitation of web extensions at the moment, because there is no API to get mouse events from browser chrome. In practice this is rarely an issue as mouse events are typically available very quickly.

You're too fast and trying to do a gesture before enough of the DOM has loaded to get MouseEvents working.
