### ISSUE TITLE
feature request: open download window, or open latest downloaded file

### ISSUE THREAD

**Issue by GianniGi** [marklieberman/foxygestures#263]
Hello, first of all thanks for this wonderful extesion.

I'd like to ask if it is possible to configure foxygestures to open the download window (ctrl-shift-y, or ctrl-j), or, even better to open the latest downloaded file. 

thanks in advance.

**Comment by marklieberman** [comment]
I don't believe it is currently possible to open the downloads window from a web extension.

Opening the latest file is possible, but it requires a specific permission `downloads.open` that Foxy Gestures doesn't have. So, I cannot do anything until the next version at least.

This user script would open the latest download if the permission was present.

```js
executeInBackground(() => {
    return browser.downloads.search({ state: 'complete', exists: true, orderBy: [ '-endTime' ], limit: 1 }).then(downloads => {
        if (downloads.length) {
            browser.downloads.open(downloads[0].id);
        }
    });
})

// Allow gesture to repeat.
let result = { repeat: true };
result;
```

**Comment by GianniGi** [comment]
Being able to download the latest file could be better than nothing, since most of the times you download one file at a time.

**Comment by marklieberman** [comment]
Added a bunch of optional permissions to be requested in af8df6c71e5bb88214e72253dc63ca50c866c0a1.

**Comment by GianniGi** [comment]
Thanks :-)

Il mar 19 mag 2020, 04:08 marklieberman <notifications@github.com> ha
scritto:
