### ISSUE TITLE
focus adress bar problem?

### ISSUE THREAD

**Issue by kevingoris** [marklieberman/foxygestures#269]
in nightly wont focus in the adressbar when gesturing newtab/hometab/etc

**Comment by kevingoris** [comment]
i normally use the nightly version and suddenly foxygestures changed it
behavior somedays ago.
Normal firefox works (new tab gesture = adress bar focus = i can write as
soon as i gesture the new tab)
Nigtly with gesture wont focus in the adress bar .... but ctrl+t will work
as intended with focus in adressbar.

**Comment by marklieberman** [comment]
Foxy Gestures hasn't had an update for a while. The issue must be with nightly. There are no APIs that allow me to address this on my end.

**Comment by Brugman** [comment]
For what it's worth. I just noticed the same focus problem on FF Developer Edition 63.0b1 and 63.0b2 for the new tab gesture. The new window gesture does focus the address bar.
