### ISSUE TITLE
Context menu is broken on Linux when gesture button is [left, middle] and chord gestures are enabled.

### ISSUE THREAD

**Issue by adam-ce** [marklieberman/foxygestures#270]
as stated, the right button menu does not work, when setting foxy gestures to use the middle button for drawing gestures.

OS: OpenSuse Linux
FF version: 61.0.2 (64-bit)
Foxy Gestures version: 1.2.1

**Comment by marklieberman** [comment]
Working fine for me on Windows. It might be a platform specific issue.

**Comment by damdamce** [comment]
erm, yes, most probably. iirc there is some special treatment of the right button for linux and macos (i remember a bugreport against ff itself).

**Comment by marklieberman** [comment]
Are you getting any errors in the browser console? Also what window system do you use in OpenSuse? Is there an ISO I you think Ishould use to build a VM for testing?

**Comment by marklieberman** [comment]
I have a VM with 61.0.1 on Ubuntu 18.04 LTS, so I did a test and the right-menu is working correctly when the gesture button is middle.

**Comment by ThomasFeher** [comment]
Same issue here running OpenSuse Tumbleweed with Firefox 72.0.1 (64-bit) and Foxy Gestures 1.2.6.

**Comment by marklieberman** [comment]
This issue is also affecting long-press on touchscreen in Windows 10.
