### ISSUE TITLE
[Feature Request] Go to Recent Tab and close the one that was just active

### ISSUE THREAD

**Issue by neube3** [marklieberman/foxygestures#279]
(I think it might be possible to implement using user functions, but these are too complex for me to handle right now.)

There is a "Go to Recent Tab" very useful gesture available; this gesture would only add "_... and close the other one_" functionality to it.

E.g.:
1. Have tabs A, B and C open
2. Focus tab C, then B, then A
3. In the tab A, perform the requested "_Close and Go to Recent Tab_" magic gesture
4. Tab B should get the focus and then tab A should get closed. 
[In this particular order, to avoid the possible overhead of closing-then-switching tabs and possibly upsetting the "recent tabs" list; I use too many tabs and I have noticed that it is basically always faster to change tabs and then close them than to close the active tab.]

Rationale: 
I often open a single "child" page to check just one thing (be it a word in a dictionary or a sub-link to have a better understanding of an article). Though this can get recursive - three child topics from one and one of those spawns its own children...

This gesture would be, effectively, "get back to parent tab, close the child tab" - very useful for Wiki-walks and any type of learning that involves "child" tabs (functions and methods with long descriptions, etc.).

**Comment by marklieberman** [comment]
Does this user script behave the way you want?

```js
executeInBackground(data => {
    return closeTabTransition(data, 'recent');
}, [ data ]);
```

**Comment by neube3** [comment]
It's perfect! And embarrassingly simple code at that (not that I could have written it myself).

Thank you!
