### ISSUE TITLE
Cause constant refresh at Norton Security site

### ISSUE THREAD

**Issue by RichS2** [marklieberman/foxygestures#289]
Logging into mynorton.com, the page goes into an repeating page refresh.  I've disabled every other add-on.  It works fine with no add-ons active and fails with just foxygestures enabled.
![Norton](https://user-images.githubusercontent.com/41040786/54848786-a2c4a300-4cb8-11e9-97a5-2ff6b793ae59.jpg)

**Comment by RichS2** [comment]
"Disable gestures for this tab" has no effect.

**Comment by RichS2** [comment]
Anyone?

**Comment by marklieberman** [comment]
See #306. Try blacklisting the URL once FG 1.2.8 is released.
