### ISSUE TITLE
Causes errors on myCigna.com

### ISSUE THREAD

**Issue by RichS2** [marklieberman/foxygestures#290]
On login, causes a screen with

 "Maintenance Notice

This page is currently unavailable. We are sorry for any inconvenience. Please bear with us while we work to correct the issue. "

on Firefox.

Logging in with Chrome works fine.  Diasabling the add-in and hitting refresh returns to normal, already logged in.  Enable/disable the add-on causes this to happen on and off within seconds of each other, tried at least 20 times over the last week - not just a matter of bad timing luck with site maintenance.

I have disabled all other add-ins and tried a clean install - this one add-in causes the problem.

**Comment by JBWJR** [comment]
Glad I found this post.  I've been experiencing the same problem and had no idea why.  Disabled Foxy Gestures and myCigna.com worked.
Thanks RichS2!

**Comment by marklieberman** [comment]
See #306. Try blacklisting the URL once FG 1.2.8 is released.
