### ISSUE TITLE
Save Link As

### ISSUE THREAD

**Issue by z1atk0** [marklieberman/foxygestures#291]
According to https://github.com/marklieberman/foxygestures/wiki/Supported-Commands-vs.-FireGestures the "Save Link As" action is already "Implemented". I can't seem to find it in the config, though - do I need a newer version, or new glasses? 8-) I'm still on 1.1.1, as I'm running FF 60.6.1esr. TIA!

**Comment by marklieberman** [comment]
Save Link As is located in the Other Commands section beside Save Media As, etc.
