### ISSUE TITLE
Foxy Gestures could not be verified for use in Firefox Developer Edition

### ISSUE THREAD

**Issue by betagoo** [marklieberman/foxygestures#294]
Foxy Gestures could not be verified for use in Firefox Developer Edition and has been disabled.
Firefox Developer Edition 67.0b16 (64-bit)

**Comment by marklieberman** [comment]
Mozilla forgot to renew an intermediate certificate related to add-on signing. Check [/r/Firefox](https://www.reddit.com/r/firefox/), its a global issue waiting for a patch.
