### ISSUE TITLE
Undo Close stopped working

### ISSUE THREAD

**Issue by arabezar** [marklieberman/foxygestures#295]
Subj.
I have no idea whether it is Firefox issue or not but the command stopped working for two weeks already (((
Manual reopening tab from recently closed tabs still works.
Does anybody have the same issue with Undo Close in FF 66.0.3 (64-bit)?

**Comment by cliftbar** [comment]
try updating to 66.0.4, I came here to comment that the whole extension broke, but noticed an update when I was checking the version I was using. Seems to have fixed whatever Mozilla busted.

**Comment by arabezar** [comment]
I dunno what was happened but everything works fine now
