### ISSUE TITLE
Feature parity with Opera12/Opera/Vivaldi

### ISSUE THREAD

**Issue by beppe9000** [marklieberman/foxygestures#297]
Open [Vivaldi ](https://help.vivaldi.com/article/mouse-gestures/#enable)and go to `vivaldi://settings/mouse/`. There are some features and gestures ("New Tab in background" among them) that could be ported to this extension.

**Comment by marklieberman** [comment]
New Tab in background has been added. Due to limited time I am mostly doing bug fixes and features by request.
