### ISSUE TITLE
foxygestures sends extra messages to iframes

### ISSUE THREAD

**Issue by pmorch** [marklieberman/foxygestures#298]
Just having foxygestures enabled sends weird messages to the iframe.

To reproduce, have parent.html:
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Parent</title>
        <script src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
    </head>
    <body>
        <iframe id="iframe" src="iframe.html"></iframe>
        <script>
            jQuery('#iframe').on('load', function () {
                let elem = document.getElementById('iframe');
                let res = elem.contentWindow.postMessage(
                    'foobar', '*'
                );
            });
        </script>
    </body>
</html>
```

And iframe.html:
```html
<!DOCTYPE html>
<html>
    <head>
        <title>iframe</title>
        <script type="text/javascript">
            function receiveMessage(event) {
                console.log('got message', JSON.stringify(event.data, null, 2));
            }
            window.addEventListener("message", receiveMessage, false);
        </script>
    </head>
    <body>
        iframe contents
    </body>
</html>
```
Opening parent.html in firefox produces this output in the console:
```
got message {
  "topic": "mg-installEventListeners",
  "data": {}
}
got message {
  "topic": "mg-frameInfo",
  "data": {
    "frameScrolling": null
  }
}
got message "foobar"
```
The two first messages only arrive if FoxyGestures is enabled. Which confuses (at least) our application since it doesn't expect any such messages. If you right-click in the parent window more messages are sent to the iframe.

(I did it on a real webserver. I'm not sure if it also happens on file:// URLs)

**Comment by marklieberman** [comment]
This is by design. As stated in the working principle of the readme.

> This extension hooks into DOM mouse events. However, each frame in a website is a separate DOM often with a separate origin. In a naïve implementation the mouse gesture would stop tracking whenever the mouse passed over an iframe.

> The solution is to have the web extension inject mouseEvents.js into every frame. Each time the script loads it will determine if it has been framed. If the script has been framed, it will establish communication with its parent frame (also running mouseEvents.js) via postMessage(). Nested instances of the script will relay mouse events up the hierarchy. As the message bubbles up the hierarchy, each script applies a coordinate offset based on the position of the nested <frame> or <iframe> element. In this way, the top-most script sees all mouse events in the coordinate space of the top-most DOM.

Post message is a cross-origin communication mechanism shared by all scripts in the scope. If your application is using it, it should check if the message is expected (e.g.: using a topic property.)

**Comment by pmorch** [comment]
If that is how the plugin is designed, then realistically, this is not going to be fixed, so lets just close the issue.
