### ISSUE TITLE
FG + Ublock Commands

### ISSUE THREAD

**Issue by ghost** [marklieberman/foxygestures#299]
Hi, I'm using Foxy Gestures addon, have an feature to use an custom script, I'm use uBlock Origin with javascripts and images ever disabled for all sites, because my net is very bad, what script I can use in Foxy Gestures to do it:

Script 1 : "Enable javascript on this site" (Per site switch) and reload page

Script 2: "Enable Images (Noop Local Rule) and reload page

someone can help me please?

**Comment by mrochaaa** [comment]
anyone?

**Comment by marklieberman** [comment]
It is not possible for FG to control uBlock directly. The only way is for uBlock to add support in their code for receiving messages from other addons. See #223 for example.

**Comment by mrochaaa** [comment]
Thanks, just an question Stylus can receive messages? You know? Is possible Toogle All Styles On-Off with FG script?

**Comment by marklieberman** [comment]
Closing since uBO will not consider implementing the required API for this to happen.
