### ISSUE TITLE
Incorrect behavior of Open Link In New Tab gesture

### ISSUE THREAD

**Issue by JuBan1** [marklieberman/foxygestures#30]
I haven't tested with other gestures, but at least Open In New Tab appears to not work in certain contexts.

[Here's a video of www.deviantart.com for illustration:](https://webmshare.com/QPOZe)

* First I used the New Tab gesture on an image link which works as long as the mouse cursor does not leave that image. However, it turns out this is just the default middle-click open action (as I'm using middle mouse for gestures).
* When leaving the image link with the mouse cursor nothing at all happens.
* Finally I used it on a text link which works fine.

I've had similar issues on other websites, for example with buttons. It seems the issues show up when the link under the mouse cursor isn't a traditional link. Is there anything that can be done about that?

PS: The popup in the bottom right shows that the correct gesture is recognized; it isn't executed though.  

I'm using FF 54.0.1 on Linux and FoxyGestures 1.0.6 directly from AMO.

**Comment by marklieberman** [comment]
I will investigate, but I think I know what the issue is. Thanks for the video, it was helpful.
