### ISSUE TITLE
Causes constant refresh at https://dmarcian.eu/login

### ISSUE THREAD

**Issue by jinnko** [marklieberman/foxygestures#301]
When attempting to view the login page the page is forced into a constant reload loop.  Turning off the addon for the tab doesn't resolve the issue and it is re-enabled at the next reload.  Only disabling the addon via the about:addons page resolves the issue.

**Comment by marklieberman** [comment]
Probably related to #306. I do not experience a constant refresh when i visited the site today, but I also do not have an account to test the actual login process.
