### ISSUE TITLE
getting to the root directory of a website

### ISSUE THREAD

**Issue by Ridbowt** [marklieberman/foxygestures#303]
Hi! Is it possible to implement the ability to go to the main page (root url, root directory, root domain) of a website? For example, we are on the page: https://example.com/one/two/three/ and we want to get directly to https://example.com/ with a single mouse gesture! It's possible now, but onerous to do so: https://example.com/one/two/three/ >> https://example.com/one/two/ >> https://example.com/one/ >> https://example.com/

**Comment by GNQG** [comment]
Create the following userscript:
```js
location.href="/"
```

**Comment by Ridbowt** [comment]
**[SOLVED]**
