### ISSUE TITLE
This extension has been blocked by firefox.

### ISSUE THREAD

**Issue by eubnara** [marklieberman/foxygestures#304]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/12639125/66969880-5a425c00-f0c6-11e9-9e0e-74cec9095d46.png">

**Comment by marklieberman** [comment]
Nothing is disabled on any of my machines, nor has Mozilla disabled anything on AMO or otherwise communicated anything to me. Unless other people can confirm something is wrong, I'd suggest it was probably something local to your machine.

**Comment by eubnara** [comment]
I noticed that on my laptop I use ubuntu and firefox. It works fine. However, I also use iMAC and firefox and I see this error on it. Maybe you're right.

**Comment by eubnara** [comment]
After reinstalling it, it works fine. Sorry for false alarm.
