### ISSUE TITLE
Foxy Gestures prevents context menu to appear by long press on a touch screen

### ISSUE THREAD

**Issue by andrewz1986** [marklieberman/foxygestures#307]
Hi. Thanks for an extension that keeps me using Firefox instead of Vivaldi. It works great in most cases, although I have an issue on Windows convertible device. In order to make context menu appear via touch on a touch screen, you usually hold a finger on the screen for few seconds. However, when Foxy Gestures extension is activated, the context menu won't appear. Is it known issue? Is it fixable? Thanks.

**Comment by salem83** [comment]
+1

same here. allthough gestures don`t even work on my touch. so the onkl option is to disable it.

**Comment by andrewz1986** [comment]
> 
> 
> +1
> 
> same here. allthough gestures don`t even work on my touch. so the onkl option is to disable it.

Disabling is not an option if you have two or more devices and use Firefox Sync. I need Foxy Gestures to work on my desktop and use the same Firefox account on my convertible notebook.

**Comment by marklieberman** [comment]
@salem83, @andrewz1986 Are you guys on Windows or Linux/OSX? 

I found a W10 machine with a touch screen and long-press is giving me a context menu.

There is a old bug #270 which breaks the context-menu on Linux when chord gestures are enabled.

**Comment by marklieberman** [comment]
This is another manifestation of #270. A quick solution is to disable chord gestures. I am investigating a fix.

**Comment by andrewz1986** [comment]
Hello, Mark. Thanks for giving an attention to this issue. I can confirm now that the issue was present on Windows 10 when chord gestures were allowed. If you provide me XPI file of latest Foxy Gestures build with the fix, I can check whether the issue is fixed on my machine. addons.mozilla.org page says that last update was done 5 months ago. This version still suffer from the issue. When will the version with a fix be released there?

**Comment by marklieberman** [comment]
@andrewz1986 A new version (1.2.7) is now published to addons.mozilla.org,

**Comment by andrewz1986** [comment]
> 
> 
> @andrewz1986 A new version (1.2.7) is now published to addons.mozilla.org,

The fix is working, thank you very much, Mark!
