### ISSUE TITLE
View Cookies

### ISSUE THREAD

**Issue by ashishkpathak** [marklieberman/foxygestures#308]
I would like to see foxygesture with the capability of viewing cookies set on the page.
Earlier, an older version of foxy gesture had that option by drawing 'C' on the page. Can we please have this feature brought back.

**Comment by marklieberman** [comment]
Unfortunately, a web extension is not able to open any of the cookie or storage related dialogs that are part of the browser. A quick alternative is perhaps to open the devtools (F12) and view the Storage tab.
