### ISSUE TITLE
Use Middle Click, Disable Scroll

### ISSUE THREAD

**Issue by jesse9212** [marklieberman/foxygestures#309]
Is there a way to disable Firefox default scroll so middle click can be exclusively used for foxy gestures?

The line doesn't draw properly and the page scrolls widely when using Middle click currently.

**Comment by marklieberman** [comment]
If you mean autoscrolling (where you middle-click and move the mouse up and down to scroll) then its a setting called "Use autoscrolling" in the Options, under the Browsing heading.
