### ISSUE TITLE
"Scroll to Bottom/Top" gestures not working properly on certain pages

### ISSUE THREAD

**Issue by MOFTAD** [marklieberman/foxygestures#31]
I've noticed that, [on certain webpages](http://firefox.add0n.com/clean-uninstall.html), the [aforementioned gestures](https://i.imgur.com/y3WsIXV.png) do not work properly.

1. "Scroll to Bottom" does not work at all on such pages.
2. Executing the "Scroll to Top" gesture results in a _downward_ scroll (i.e., the "Scroll to Bottom" gesture).

There are only a few pages upon which this seems to occur. I've tested on a new profile with only Foxy Gestures installed, and the issue persists.

**Comment by marklieberman** [comment]
I'm not able to reproduce. Can you tell me what edition of Firefox you are using? Also, in the example page you linked the entire comments section is an iframe with scrolling="no". It may be necessary to change or split "Scroll to Top" into something like "Scroll Frame to Top".

**Comment by MOFTAD** [comment]
I'm on Nightly 57.0a1 (2017-08-08), Windows 10. I've also tested on 54.0. I don't know if my mind is playing tricks on me, but the behaviour is different now (albeit still not functioning properly). Both bottom and top are scrolling to top on the page.

**Comment by marklieberman** [comment]
I published version 1.0.7beta2 to the development channel on my AMO page. I was not able to reproduce the issues, but I refactored and improved some of the code in a way that might have solved it. Let me know if the problem remains.

**Comment by MOFTAD** [comment]
The problem does indeed remain. Seeing as how you are unable to reproduce the issue, it must be a result of something on my end. Regardless, thank you.

**Comment by marklieberman** [comment]
I figured out the source of this problem. The example page you provided has the HTML element with height: 100% and the body with overflow: scroll. This causes document.documentElement.scrollTop to always be 0. This causes the scroll offset calculation to be wrong and scroll up when it should go down.

**Comment by kRush-** [comment]
https://www.twitch.tv/
https://www.inoreader.com/all_articles (requires account)
are other examples where scroll to top/bottom does not work.

**Comment by marklieberman** [comment]
@kRush-  The issue with both of those example is that they are using CSS and JavaScript trickery to scroll content inside a container. I'm not sure how familiar with HTML/CSS you are, but to put it simply most pages are tall and the browser window has scroll bars. In those example sites, the page is the size of your browser window and has its "own window" where scrolling happens. I'll think about how to fix this but its actually a very difficult problem to handle in a general case.
