### ISSUE TITLE
[Feature Request] Open Link in New Background Tab or New Tab

### ISSUE THREAD

**Issue by irahsu** [marklieberman/foxygestures#317]
Can we have a new hybrid built-in command for "Open Link in New *Background* Tab or New Tab"? We already have the "Open Link in New Foreground Tab or New Tab" option, but I like to open background tabs for links that appear in the middle of an article that I would like to follow up with when I am done reading the current page.

Thank you for your work on this!

**Comment by marklieberman** [comment]
I'll consider adding it as a hybrid command, but this user script will do it in the meantime:
```
executeInBackground(data => {
    if (data.element.linkHref) {
        commandOpenLinkInNewBackgroundTab(data);
    } else { 
        commandNewTab(data);
    }    
}, [ data ]);

```

**Comment by irahsu** [comment]
Thanks! The user script works awesomely! 👍
