### ISSUE TITLE
No contextual cursor change after using gesture in Firefox 78.0.1

### ISSUE THREAD

**Issue by rottenkumquat** [marklieberman/foxygestures#318]
After using a gesture the contextual cursor icon (for links, selecting texts) often gets stuck in Firefox 78.0.1. Reloading the page fixes it. But not for long.

**Comment by AndrewNile** [comment]
I'm also seeing this on Foxy Gestures 1.2.7 & Firefox 78. It didn't happen in 77.

The easiest way I've found to reproduce this is to open two tabs with content, then perform the close gesture. When the other tab becomes selected, the cursor doesn't react to the page (as stated by @rottenkumquat, hand for clickable links, serif I for text).

Moving the cursor over a part of Firefox's chrome (address bar, bookmarks bar, etc) unsticks it.

**Comment by tanrak** [comment]
See also https://github.com/Robbendebiene/Gesturefy/issues/514

**Comment by marklieberman** [comment]
I reported a similar issue a couple years ago, but nothing came of it.
https://bugzilla.mozilla.org/show_bug.cgi?id=1466009

**Comment by yoasif** [comment]
Per [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1650657), this is fixed in Firefox 79. You can upgrade to beta if you want the fix now.

**Comment by tanrak** [comment]
I think this issue can be closed now.
