### ISSUE TITLE
Nordea.fi netbank new version fails to confirm payments when Foxy Gestures is enabled

### ISSUE THREAD

**Issue by toejam119** [marklieberman/foxygestures#319]
For some reason the new version (as of early 2020) of Nordea(.fi) netbank fails to confirm payments when Foxy Gestures addon is enabled in Firefox 78 stable and Firefox 79 beta, Win10 x64, not sure if applies in earlier versions of Firefox. I just get a red error saying (in Finnish) "confirmation failed". If I disable the addon confirmation works fine.

**Comment by marklieberman** [comment]
This is probably related to what I commented #306. It is very hard to debug specific sites that require a login, so I cannot know for sure. If you are still using FG, try updating to 1.2.8 when it gets released shortly and use the blacklist option to disable it on Nordea.fi.
