### ISSUE TITLE
Suggested command: Back to last page of previous host.

### ISSUE THREAD

**Issue by PWilsonGorge** [marklieberman/foxygestures#322]
If you are deep into a particular web site and want to backup to the previous web site your only option is to right click the back button and select from the drop down. (good luck with that if you have just watched a 30 slide lecture). I can't remember which, but a previous mouse gestures add-on had this command.

**Comment by marklieberman** [comment]
Unfortunately, that level off access to history is not available in web extensions and I do not want to have my addon record your browser history even if it is only for this feature. For that reason it is unlikely that I can implement this feature.
