### ISSUE TITLE
spiegel.de confirmation not working with foxygesture activated

### ISSUE THREAD

**Issue by Zsigmondy** [marklieberman/foxygestures#324]
On spiegel.de you have to do an confirmation on the first use of the site. With FoxyGesture activated, the button for confirmation is missing
![w_Foxy](https://user-images.githubusercontent.com/8626368/91092461-596c4600-e658-11ea-892b-8cbe853e268b.jpeg)
![w_o_Foxy](https://user-images.githubusercontent.com/8626368/91092463-5a9d7300-e658-11ea-9943-2fd49ce51705.jpeg)

**Comment by pitgrap** [comment]
Took me one week to find out, that this plugin is causing the problem...

**Comment by marklieberman** [comment]
See #306 for my comment about why its broken.
