### ISSUE TITLE
Adding about 700 bytes scripts causes not to save option.

### ISSUE THREAD

**Issue by Via-GitHub** [marklieberman/foxygestures#326]
Currently, Foxy Gestures does not seem to save largish user data. After you add user scripts of 600-700 bytes or more in total, the whole of Option is no longer saved. I tried with 2 profiles and confirmed the reproducibility.

Firefox Developer Edition 81.0b6

**Comment by valeriocirioni** [comment]
For me it's the same. I had few long scripts working nicely, but i wanted to change few lines.
I then tryed to modify one, but it wasn't updating at all. So I made a backup, delete everything and restored.
The scripts are regularely restored, but then they are not saved and get discarded once the page is reloaded.
Now I find myself without any useful script.

Have you found any workaround yet?

**Comment by marklieberman** [comment]
The issue seems to be changes to storage.sync that landed in Firefox 79. I'll probably have to migrate user scripts to storage.local since the new limits are pretty low.

https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/
