### ISSUE TITLE
Feature request: jump (as opposed to scroll) to bottom/top of the page ...

### ISSUE THREAD

**Issue by z1atk0** [marklieberman/foxygestures#328]
... like hitting the "home" or "end" key on the keyboard, but without having to take my hand off the mouse. This would be great, especially on loooooooooong pages and/or pages with looooooooots of images.

It takes ages (or at least feels like it) to scroll through. If I want to get to the top/bottom of the page, I want to get there as fast as possible, and I'm not interested in seeing the page content pass by while I'm on the way there. Or is it just me? Probably not. ;-)

**Comment by marklieberman** [comment]
https://github.com/marklieberman/foxygestures/issues/311#issuecomment-620097601
