### ISSUE TITLE
First right click on newly loaded page ignored for one time, then opens context menu.  Gesture button is middle mouse, not right click.

### ISSUE THREAD

**Issue by okumam** [marklieberman/foxygestures#329]
Windows 10, Firefox 80 and the issue has been present a long time.
Gesture invoker is middle mouse key, NOT right mouse button.

When a page is loaded for the first time, right click input is completely ignored, instead of the expected behavior of opening context menu.  You have to right click again to get the context menu.

Once this happens, further right clicks work as expected, bringing up context menu.  This only happens once, and only when a tab is loaded.

Disabling the addon eliminates the issue.

Any other information I can provide?

**Comment by marklieberman** [comment]
I can confirm the bug. FYI a simple workaround is to enable "Chord gestures" even if you have no chord commands defined.
