### ISSUE TITLE
"New Tab" behaviour of 1.2.8 is weird/broken.

### ISSUE THREAD

**Issue by soulsource** [marklieberman/foxygestures#332]
1.2.7 is working fine, but 1.2.8 opens all new tabs as sub-tabs of the current one, causing issues if used together with other addons like TreeStyle Tab.

Behaviour after opening a new tab using version 1.2.7:
![grafik](https://user-images.githubusercontent.com/3518676/95549611-e0f2f600-0a07-11eb-951a-79fe7782980f.png)

Same commands, same situation, and same settings with version 1.2.8:
![grafik](https://user-images.githubusercontent.com/3518676/95549593-dafd1500-0a07-11eb-91ae-cc8bbaafffe9.png)

**Comment by marklieberman** [comment]
Looks like the PR that added the search for selection commands (a3363e3ebab1e71c72881dfa531f3347ea1d540c) changed how New Tab was implemented. I will revert that change shortly.

**Comment by marklieberman** [comment]
Closed by ca69c00b26d4935b638ed4c2ddeda946abd5e6de and a new version published to AMO which should be available as soon as it is approved.
