### ISSUE TITLE
1.2.8: "New Tab" gesture ignores browser.tab.insertAfterCurrent

### ISSUE THREAD

**Issue by z1atk0** [marklieberman/foxygestures#333]
Since yesterday's update to 1.2.8, opening a new tab via gesture seems to ignore Firefox' `browser.tab.insertAfterCurrent` setting. I have mine set to `false`, and opening a new tab via gesture still opens right next to the current tab. All other ways of opening a new tab (the "+" button in the tab bar, the `Ctrl+T` shortcut, the `File -> New Tab` menu entry) still work as expected, so I think it's not Firefox' fault.

I don't know if `browser.tab.insertRelatedAfterCurrent` is also affected or not, because I open links in new tabs with a middle mouse click, not with a gesture.

This is on FF 78.3.1esr (32-bit) & Foxy Gestures 1.2.8.

**Comment by marklieberman** [comment]
Can you update to 1.2.9. There was unintentional change to New Tab command in 1.2.8. See #332.

**Comment by z1atk0** [comment]
Thanks, auto-update already installed 1.2.9 meanwhile, and things are back to normal again! :+1: :smiley:
