### ISSUE TITLE
wheel gestures: define scroll "steps"

### ISSUE THREAD

**Issue by andreev-dmitry** [marklieberman/foxygestures#336]
hello! 
There is a problem with the wheel gestures settings: I used to use mouse wheel scroll with the right button to navigate between tabs. When I scroll down once (one step) — the tabs "run" VERY quickly from one to another till I press the right button. 

Is it possible to use the **one** "wheel step" for **one** "tab change" **AND** keep RB pressed? — so, to be possible to move between "next"/"previous" tabs with the pressed RB. 

Thanks in advance!
_ps: this function works well in firegestures with the same OS mouse settings in ff-56._

**Comment by marklieberman** [comment]
Works as expected for me. I hold right button and scroll up and down to switch tabs, one tab per wheel tick. Does your browser scroll normally when using the mouse wheel to scroll up and down a page? Same amount each tick of the wheel?

**Comment by andreev-dmitry** [comment]
**Sorry for inconvenience: my fault.** There was a conflict with the other mozilla add-on ("Logitech SetPoint"). Now everything is Ok, Add-on works perfectly!
Thank You for your work and support! I like this addon very much! 🥇
