### ISSUE TITLE
Weird glitch on scrollbar using wheel gestures

### ISSUE THREAD

**Issue by i2324561w2** [marklieberman/foxygestures#338]
Go to https://www.reddit.com/r/Android/comments/jpgv0v/lets_encrypt_wont_support_android_7_and_below_by/gbfaygo/ with scroll up/down enabled on "enable wheel gestures" and "Amount of viewport to scroll for Scroll Up/Down commands"=99, use it to scroll up and down: the scroll bar gets kind of messy. I'm also on the old layout of reddit (via its settings).

**Comment by marklieberman** [comment]
I tried it as you described but I can't reproduce anything out of the ordinary.

**Comment by i2324561w2** [comment]
I also have "Duration of the animation for the Scroll family of commands"=100, also it doesn't appear only on reddit.
If you can't see it then it can be closed, the issue must be on my profile.

**Comment by marklieberman** [comment]
I tried it again with scroll duration of 100ms just to be sure, but I am still unable to make the scroll bar freak out or otherwise do anything strange. Feel free to re-open the issue if you find any new information that could help me reproduce it.
