### ISSUE TITLE
Using wheel gestures for next/previous tab also scrolls page a small amount

### ISSUE THREAD

**Issue by KernelLeak** [marklieberman/foxygestures#339]
Lately, I've noticed that using the scroll up/down wheel gestures for next/previous tab also scrolls the page by a small amount, which is quite annoying when switching between two tabs repeatedly. (Especially noticeable when opening two instances of the same page at the same scroll position, then switching back and forth repeatedly...)

Could it be that something has changed in Firefox lately so the wheel gesture doesn't completely cancel the default action? (Using Firefox Developer 84.0b6)

I know I might be barking up the wrong tree here, so to speak, but I wouldn't know where to begin reporting this in Bugzilla... :(

**Comment by KernelLeak** [comment]
Well, scratch that - I've found the problem:

https://bugzilla.mozilla.org/show_bug.cgi?id=1673278

Disabling dom.event.default_to_passive_wheel_listeners fixes the problem, but since that's the new default it'll probably cause more problems down the line when it hits the release channel... maybe there's a workaround you can implement in Foxy Gestures? :(

**Comment by KernelLeak** [comment]
Going out on a limb here: would changing 

https://github.com/marklieberman/foxygestures/blob/673b6eff222ef48de580152a2b7159813fdb6e1d/src/content/mouseEvents.js#L123

to
```javascript
window.addEventListener('wheel', onWheel, { capture: true, passive: false });
```
fix this?

**Comment by marklieberman** [comment]
@KernelLeak That does appear to fix the issue when I test it in Nightly. I have to test it a bit more since there are a few other mouse handlers can call preventDefault() and will require `passive: false`. I will publish a new version of FG as soon as I am able.

**Comment by KernelLeak** [comment]
Thanks! This was driving me crazy... 👍
