### ISSUE TITLE
Does not save changes in FF 56.0b2

### ISSUE THREAD

**Issue by RedSnt** [marklieberman/foxygestures#34]
Extension does not seem to save settings made to built-in gestures. I tried changing New Tab to Down gesture, and nothing was saved.  

Someone else reported the same bug [here](https://addons.mozilla.org/en-US/firefox/compatibility/reporter/%7Be839c3f9-298e-4cd0-99e0-464431cb7c34%7D).

**Comment by marklieberman** [comment]
I am aware, thank you. Please see: https://github.com/marklieberman/foxygestures/issues/26

You can use the beta version from AMO until the next release is approved.

**Comment by RedSnt** [comment]
Yeah, just found the developer version where it is working. Thanks for the quick reply.
