### ISSUE TITLE
[Windows][FF 84.0 x64] Undo Close Tab gesture not working (anymore)

### ISSUE THREAD

**Issue by e-d-n-a** [marklieberman/foxygestures#341]
I had no issue with FoxyGestures so far and have used it for years!
Suddenly, undo close tab doesn't work anymore on any website/tab.
Default "Ctrl+Shift+T" works without issues tho...
Also list of "recently closed tabs" in the chronic is filled and appears normal.

The recognized command appears in the corner of the browser, but nothing happens.
I get this error in the browser console, that appears on every try:

![2020-12-18 11_49_14-Browser-Konsole](https://user-images.githubusercontent.com/8239937/102607907-5b877280-4129-11eb-9a88-15ea1b1526f2.png)

```
entry is undefined ext-browser.js:962
    convertFromSessionStoreClosedData       chrome://browser/content/parent/ext-browser.js:962
    tabs                                    chrome://browser/content/parent/ext-browser.js:1175
    map                                     self-hosted:221
    convertFromSessionStoreClosedData       chrome://browser/content/parent/ext-browser.js:1174
    getRecentlyClosed                       chrome://browser/content/parent/ext-sessions.js:34
    getRecentlyClosed                       chrome://browser/content/parent/ext-sessions.js:122
    AsyncFunctionNext                       self-hosted:674
    (Async: async)
    getRecentlyClosed                       self-hosted:1161
    result                                  resource://gre/modules/ExtensionParent.jsm:958
    withPendingBrowser                      resource://gre/modules/ExtensionParent.jsm:489
    result                                  resource://gre/modules/ExtensionParent.jsm:958
    callAndLog                              resource://gre/modules/ExtensionParent.jsm:920
    recvAPICall                             resource://gre/modules/ExtensionParent.jsm:957
    AsyncFunctionNext                       self-hosted:674
    (Async: async)
    recvAPICall                             self-hosted:1161
    _recv                                   resource://gre/modules/ConduitsChild.jsm:78
    receiveMessage                          resource://gre/modules/ConduitsParent.jsm:371
```
    
    It may have started after installing another addon, but I'm not sure.
    https://addons.mozilla.org/en-US/firefox/addon/select-after-closing-current/
    
    I tried deactivated it (also other addons) and restarted tho without luck!
    I also raised the amount of restorable windows recently, but not tabs I believe (probably unrelated).
    
    Maybe you have an idea, if it's related to my setup or an issue with FoxyGestures?
    I can't get anything out of this error message myself.

**Comment by marklieberman** [comment]
I found this bug on Bugzilla. There is a link to instructions to fix the issue in the most recent comment.

https://bugzilla.mozilla.org/show_bug.cgi?id=1509701

It looks like a problem with Firefox internals, not with Foxy Gestures. The stack trace you posted is all Firefox internals with no references to Foxy Gestures scripts.

**Comment by e-d-n-a** [comment]
OK, thx for pointing me in the right direction!

I will try this fix as soon as I can:
https://github.com/M-Reimer/undoclosetab/wiki/How-to-fix-broken-browser-session

I will report back, if it solved this issue.
