### ISSUE TITLE
How can I enable this add-on for blank pages and other such areas it doesn't work in?

### ISSUE THREAD

**Issue by doobersn** [marklieberman/foxygestures#35]

**Comment by marklieberman** [comment]
it is not possible for web extension addons to operate in those areas at this time. it cannot be done.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by marklieberman** [comment]
you can change the default URL for new tabs opened by Foxy Gestures to a normal site like Google for example. it's in More Preferences tab
