### ISSUE TITLE
Max zoom level of Firefox not honored by foxygestures' zoom function

### ISSUE THREAD

**Issue by GSF1200S** [marklieberman/foxygestures#355]
Debian, Firefox-esr.

zoom.maxPercent set to 500, and toolkit.zoomManager.zoomValues set to .3,.5,.67,.8,.9,1,1.1,1.2,1.33,1.5,1.7,2,2.4,3,3.5,4,4.5,5

Foxygestures (using a wheel gesture via right click + scroll up/down) will scroll all the way up to 300 and then stop. If I use Firefox's built-in zoom function however, I can further get 350%-500%.

This is an issue with high resolution screens (say 2k on a 24", or perhaps 4k on a 27") when a website uses particularly small fonts or formats.

I propose that either foxygestures parses the values stored in about:config as listed above, or that you add a maximum zoom level option in foxygestures preferences (this would probably be more simple and would work with your existing zoom increment feature of "Amount to change zoom factor for Zoom In/Out commands")...

**Comment by marklieberman** [comment]
The documentation states that zoom must be between 0.3 and 3.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/setZoom

I have not tested a value larger than 3 since the command was first written so it is possible that the documentation is out of date.
