### ISSUE TITLE
Undo Close Tab undoes closed window

### ISSUE THREAD

**Issue by Velenir** [marklieberman/foxygestures#358]
Undo Closed Tab gesture sometimes reopens closed tab and sometimes closed window.

I made sure the gestures don't overlap and tabs and windows are correctly listed in `History > Recently closed (tab | window)` respectively.
Firefox own shortcuts `Ctrl+Shift+T` for tabs and `Ctrl+Shift+N` for windows work correctly.

Undo Closed Window gesture works correctly and only reopens windows.

**Comment by marklieberman** [comment]
I cannot reproduce any issue using the following steps:

1. From existing window, open a new window
2. Navigate to reddit.com in new window
3. Close window
4. Gesture: Undo Close Tab

Or

1. From existing window, open a new window
2. Navigate to reddit.com in new window
3. Open a second tab and navigate to youtube.com
4. Close youtube tab
5. Close reddit tab
6. Gesture: Undo Close Tab

I tried a couple variations of the above, but behaviour was correct in each case. It would be helpful if you could find a set of steps to reproduce the issue.

**Comment by Velenir** [comment]
After a bit of investigation It was happening to me when new window was opened in a PopUp with `window.open`
But today I can't reliably reproduce it

Will close this issue for now and reopen if I can repro.

Sorry to bother you :disappointed:
