### ISSUE TITLE
Add locales

### ISSUE THREAD

**Issue by rubcap** [marklieberman/foxygestures#37]
Hi,

First of all, great work on this FireGestures replacement!
The options page is neat and an example of how it should be done!
Thank you for all the work already done.

Please let me know if I can help you translate your add-on to Dutch.

**Comment by marklieberman** [comment]
Thanks for the offer. I need to become familiar with the localization API but I will definitely get your help once I start work on localization.

**Comment by marklieberman** [comment]
I've localized all of the strings on the gesture handling side of the addon. I just need to localize the options UI. Should be ready in a few days.

**Comment by rubcap** [comment]
Hi,
Let me know if and how I can help translating your add-on.
Best regards

**Comment by marklieberman** [comment]
@rubcap I just added a few missing strings to messsages.json. You can go ahead and start localizing it whenever you want to begin. Thanks.
