### ISSUE TITLE
does this still work on latest build?

### ISSUE THREAD

**Issue by ypurpl** [marklieberman/foxygestures#376]
I get the trail thing, but nothing happens, I also can't find a place to edit gestures

**Comment by T1mL3arn** [comment]
It is possible that foxygestures settings was reseted. I got similar problem recently. 

You can setup gestures there:
![image](https://user-images.githubusercontent.com/9349164/201820862-65ba91e9-8652-411b-a025-ae2b8c68d6df.png)

To open the settings:

- right click on addon's icon
- click "Manage Extension"
- click `...` button
- click "Options"

**Comment by ypurpl** [comment]
for some reason I couldnt find the options panel until now, thanks anyway. Im on my laptop rn so I dont have a mouse, I'll test when I get home
