### ISSUE TITLE
Add zoom in / zoom out options in mouse wheel gestures.

### ISSUE THREAD

**Issue by grssam** [marklieberman/foxygestures#39]
I really like the ability to scroll up/down while holding the right click to easily zoom in the page. Very handy when you have to quickly focus on something.
All three options can be added and assigned to scroll up/down:
* zoom in
* zoom out
* zoom reset
Corresponding Web Extension API is https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/setZoom

**Comment by marklieberman** [comment]
Note that you can configure the zoom factor in the More Preferences tab. Default is to change by 10%.

**Comment by grssam** [comment]
Great Thanks!
