### ISSUE TITLE
Scrolling mouse gestures?

### ISSUE THREAD

**Issue by AlHollandiyah** [marklieberman/foxygestures#43]
Is there a way to set scrolling mouse gestures without the wheel? I wanted to set them like fire gestures, single up and single down, but I found only options that use the wheel. My mouse doesn't have a wheel, so I can't use any of those options.

**Comment by marklieberman** [comment]
I just wrote scroll up and scroll down gestures yesterday. They will be in the next version of Foxy Gestures. See #38.
