### ISSUE TITLE
mouseDown.target missing in the latest 1.0.8beta4 version on AMO

### ISSUE THREAD

**Issue by grssam** [marklieberman/foxygestures#47]
Thus, any thing relying on that fails, like user scripts.

**Comment by marklieberman** [comment]
I know, I refactored some content scripts when I fixed wheel gestures and accidentally dropped the getter for the mouseDown reference. I noticed it when testing my own user scripts, but didn't get around to fixing it yet. I can publish a beta5 if this is currently blocking you.

I want to write unit tests to catch things like this, but last time I started it was a huge job just mocking out the web extension APIs in a testable way.

**Comment by grssam** [comment]
yeah, it would be a great help if you can put it back. I really want the new mouse wheel gestures while on the other hand, i have some really complex user scripts that i want to retain.

**Comment by marklieberman** [comment]
I pushed beta5 to AMO. Please try it and let me know.

**Comment by grssam** [comment]
beta5 works. Thanks a lot! You can close this issue with the actual commit.
