### ISSUE TITLE
[BUG] Restore backed up settings makes the addon "hang"

### ISSUE THREAD

**Issue by RedSnt** [marklieberman/foxygestures#48]
Versions: FF 56.0b10 (64-bit) and FG 1.0.8beta4

I had to do a profile refresh a couple of days ago so I made backups of all my extensions, and making backups work just fine, but restoring the backup makes the addon "hang" - as in, FF is fine, but on the addon page where you restore the backed up settings the addon just hangs. FG seems to work fine otherwise, but it will not import the settings.

regards, Brian L

EDIT: Loving FG - luckily I only had like 3 gestures to change to my liking.

**Comment by marklieberman** [comment]
It's Mozilla's fault for enabling out-of-process web extensions by default on windows when it wasn't ready. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1385548

You need to set "extensions.webextensions.remote" to false in about:config, or any addon that uses JavaScript's alert() or confirm() dialogs in the addons UI will hang.
