### ISSUE TITLE
New command: Reload (bypass cache)

### ISSUE THREAD

**Issue by Matthewus** [marklieberman/foxygestures#49]
Hi!
Feature request: add the ability to create a gesture for Reload (override cache) command.
Possbile bug: using the Save media now command, the downloaded files doesn't show up in Firefox, the indicator doesn't glow up, but the file is downloaded properly.

**Comment by marklieberman** [comment]
I can do the reload (bypass cache command) for you.

As for the download issue, that part is up to Firefox. I just call `downloads.download({ url: ... })` and the actual downloading and UI stuff is all Firefox.

**Comment by Matthewus** [comment]
Thanks for the quick reply. The download issue is interesting, because with FireGestures i can see what i downloaded and with Foxy Gestures i can't. I will try it with a clean profile, maybe this is a Firefox bug.
