### ISSUE TITLE
Add custom mouse gestures

### ISSUE THREAD

**Issue by happysurf** [marklieberman/foxygestures#5]
Is possible add custom gestures like "Open image in a new tab" or something like that, or you will provide in the future more gestures like this?
Thanks for create a gestures WE alternative extension.

**Comment by marklieberman** [comment]
I just committed this feature last night for #1. I am just doing testing and I have to write documentation to explain the use of functions like `executeInBackground()`. Here is a preview of the feature:

![custom](https://cloud.githubusercontent.com/assets/6473247/25435822/65ceb184-2a5f-11e7-9364-cf24f6473948.png)

**Comment by marklieberman** [comment]
User scripts have been implemented. [The feature is documented on the wiki](https://github.com/marklieberman/foxygestures/wiki/User-Scripts)

Version 1.0.3 is pending review on AMO so this feature should be published in a few weeks.

**Comment by happysurf** [comment]
I hope to see in the future in wiki section or in a new post, a custom gestures collection request by users.
Thanks.

**Comment by marklieberman** [comment]
Just to provide an update on this issue. I submitted a new version to AMO over a month and a half ago. After waiting a couple weeks for a review it was immediately rejected over the use of `eval()` function to implement user scripts. In Web Extensions, `eval()` or the Function constructor are the only ways to execute user provided scripts.

I spoke to a reviewer in the IRC channel and he agreed to perform a more in depth review. I have resubmitted the addon to AMO after adding some warning dialogs to the user script section. However I have been waiting a few weeks for another review.

It seems that Mozilla does not have a policy on how to review extensions that do user scripts like Foxy Gesture or extensions similar to Greasemonkey.

**Comment by happysurf** [comment]
The review waiting is really too long for the new version, you are right about the policy because in the meantime there are other WE extensions like Gesturefy or smartUp Gestures that have passed the AMO review.
If the gesture scripts are the same or similar I don't understand because your extension have problems for pass the AMO review.
This is very annoying for the users and also for you of course.
