### ISSUE TITLE
Container Tabs Not Supported

### ISSUE THREAD

**Issue by unicorndreams** [marklieberman/foxygestures#55]
I have just discovered Firefox Container Tabs and I'm addicted to them! The problem is, Foxy Gestures open links either on new tabs or new windows on the default container. It would be nice to have an option to open all new tabs or windows in the same container as the originating Page.

**Comment by marklieberman** [comment]
I found some example projects showing how to open tabs in containers, but not any good documentation on MDN. I'll see what I can do.

**Comment by unicorndreams** [comment]
Thank you very much, and congratulations on finding that, I'm still having a hard time looking for the seldom documentation of container tabs. It's amazing Firefox has such powerful identity control and almost no support to it!
