### ISSUE TITLE
Gestures unavailable in FF-specific pages (e.g. about:addons)

### ISSUE THREAD

**Issue by Ceremony64** [marklieberman/foxygestures#58]
Unfortunately, one cannot use any mouse gestures on pages provided by Firefox itself, such as about:addons or about:config. It also applies to error pages generated by Firefox (e.g. "The connection was reset") and the integrated reader (about:reader), which parses the content of a website to make it less distracting and more readable.

**Comment by marklieberman** [comment]
This is a known issue for all web extension gesture addons and is clearly stated in the addon description.
