### ISSUE TITLE
[Help] 'Search for Selection' user script

### ISSUE THREAD

**Issue by Faberman** [marklieberman/foxygestures#62]
I've noticed in the Wiki that this gesture is not planned at all: `Search for Selection | Not Planned`
Is it possible to write a user script to imitate this gesture from FireGestures? Does Firefox 57 have a required API?

Here is a demo of FireGestures's gesture. Very quick and very useful.
https://dl.dropboxusercontent.com/s/v55tiumpwblqtey/firegestures_search.gif

**Comment by marklieberman** [comment]
You could have a user script do that, but you have to inject all of the UI for the menu into the page as HTML manually. There is no "ready-made" custom context menu function in web extensions. Eventually I'll have some kind of popup menu when I implement #8 but I am very busy and it is low priority for me at the moment.

In terms of effort required to pull this off, I think you'd be better off using another web extension that adds it to the standard context menu.

**Comment by Faberman** [comment]
Ok, I see. Maybe i'll wait for your popup implementation then. Anyway I still use Firefox 54 and just started to looking for legacy addons replacements.

> There is no "ready-made" custom context menu function in web extensions

Actually, it seems WE have a popup and CSS framework. You can enable it with `"browser_style": true` key in manifest.js. And then it will be possible to use 'native' styles like  `class="panel-section panel-section-list"` ([Firefox Style Guide](http://design.firefox.com/StyleGuide/#/navigation)). I've tested ['latest-download'](https://github.com/mdn/webextensions-examples/tree/master/latest-download) example extension in Nigthly 58 and it works fine.  I'm not sure if all this stuff is useful though.

**Comment by marklieberman** [comment]
The browserAction and pageAction APIs are specifically for the buttons that appear in or next to the address bar. The menus API adds an item to the native context menu. None of those APIs may be used to create a custom context menu over an element in the page.  Also, those built-in browser classes are not available in the DOM and if they were it wouldn't be very useful. One of the biggest challenges of injecting elements into a page is dealing with the page's own CSS styles being applied to the injected elements. I'll make a note to implement Search for Selection command in #8 for when I eventually get to it.

**Comment by Faberman** [comment]
Thank you for the clarification. Things are more complicated than they seem.

**Comment by mayaka227** [comment]
/* Foxy Gestures UserScript */
var src = window.getSelection().toString()
if (src) {
    if (src.indexOf("http") != 0) {
        src = "https://encrypted.google.com/search?q=" + src;
    }
    executeInBackground(src => {
        getActiveTab(tab => browser.tabs.create({
            url: src,
            index: tab.index + 1,
            active: true
        }));
    }, [ src ]);
}

**Comment by marklieberman** [comment]
@mayaka227 See also #93
