### ISSUE TITLE
Add a gesture to go to the home page

### ISSUE THREAD

**Issue by jwannebo** [marklieberman/foxygestures#65]
Only gesture I'm missing from FireGestures

**Comment by marklieberman** [comment]
There is no way for a web extension to retrieve your home page from settings. This means I cannot make a "Go Home" command that works for everyone. However, you can easily add a user script to go to any URL you want. Enter the following in user scripts and supply the home page URL you desire.
```javascript
executeInBackground(() => {
   getActiveTab(tab => browser.tabs.update(tab.id, { url: 'http://www.reddit.com' }));
});
```

**Comment by marklieberman** [comment]
Reopening because this might be possible after all, but will require additional permissions. I haven't tested it yet.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserSettings/homepageOverride
