### ISSUE TITLE
FireGestures script -> Foxygestures

### ISSUE THREAD

**Issue by tr56** [marklieberman/foxygestures#66]
Hello!
There is any way to remake this FireGestures script to Foxygestures compatible script?
it is open youtube links in the potplayer and i can't imagine how to use Firefox 57+ without this script

const APP_PATH = "C:\\W1\\Progs\\PotPlayer\\PotPlayerMini.exe";

var srcNode = FireGestures.sourceNode;
var linkURL = FireGestures.getLinkURL(srcNode);
if (!linkURL)
  throw "Not on a link";

var file = Cc["@mozilla.org/file/local;1"].createInstance(Ci.nsILocalFile);
file.initWithPath(APP_PATH);
if (!file.exists()) {
  alert("File does not exist: " + APP_PATH);
  return;
}
var process  = Cc["@mozilla.org/process/util;1"].createInstance(Ci.nsIProcess);
try {
  var args = [linkURL];
  process.init(file);
  process.run(false, args, args.length);
}
catch (ex) {
  alert("Failed to execute: " + APP_PATH);
}

**Comment by marklieberman** [comment]
Sorry, but web extensions can not run external programs directly. You cannot directly port that script to Foxy Gestures.

The closest way I can think of to make it happen is: 
1) Make a brower addon that uses [Native Messaging](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging) to invoke a small native app and pass the YouTube URL.
2) Write a native app (using node.js for example) that takes the YouTube URL and uses it to launch PotPlayer.exe.
3) Have a Foxy Gestures user script send a message to your browser addon using `browser.runtime.sendMessage()` with your addon's ID and the YouTube URL.

If you are new to web development it may be a neat little project to learn. If you're not, then it shouldn't be that difficult. Best of luck.
