### ISSUE TITLE
Should work in “technical” tabs like FVD Speed Dial

### ISSUE THREAD

**Issue by Mercury13** [marklieberman/foxygestures#72]
Mouse Gestures Suite works in all tabs.
FoxyGestures works only in tabs with pages.

**Comment by marklieberman** [comment]
Mouse Gestures Suite is a legacy extension and could modify whatever it wanted. Foxy Gestures is a web extension and is not permitted to modify internal pages like about://, or moz-extension://. Therefore, I cannot support gestures on internal pages at this time.
