### ISSUE TITLE
can't longer add userscripts

### ISSUE THREAD

**Issue by gesturesUser** [marklieberman/foxygestures#73]
I had two userscripts installed, which have been working. Now I deleted them, because I solved that problem in other ways.
Now i tried to install a new userscript, but taht is not longer possible:
Clicking the blue "Add User Script" Button does not open the possibility to add new scripts.
Thats also true for a reinstallation for foxygestures in that Firefox profile, where I also will not see (after reinstallation) the red warning before the first userscript.

How can I fix that?

**Comment by marklieberman** [comment]
Can you open the devtools on the addons settings page (press F12) and tell me if it gives any errors when you press the "Add User Script" button?

Also, can you backup your settings using the button on "Backup & Restore" tab and post the file contents here?
