### ISSUE TITLE
Trails don't show on pages with NoScript disabling JS

### ISSUE THREAD

**Issue by jamesisaac** [marklieberman/foxygestures#75]
If I have the NoScript add-on disabling scripts on a page, the gesture trails don't show.  The gestures do still work, and the status text appears, but it's a little disorientating not having a trail appear (makes it seem like it's not working).

Could there be any way round this, or is it a limitation of WebExtensions?

**Comment by marklieberman** [comment]
This is a limitation of Firefox at the moment as it doesn't know how to differentiate between regular DOM and DOM added by content_scripts when applying CSP. I believe there are some open Bugzilla bugs to fix this behaviour but I am not 100% sure.

**Comment by jamesisaac** [comment]
Ah, that's a shame.  Thanks for the quick update.  The trails are working with or without JS in FireGestures, but I see that's not supported on FF57+, so I guess achieved through an outdated API?

**Comment by marklieberman** [comment]
FireGestures was modifying the browser chrome. The trail was part of the browser UI. Web extensions are designed to prevent addons from modifying the browser UI (except for very specific cases) so it is no longer possible to draw the trail in the browser UI. Instead the trail is drawn in the webpage using a canvas element injected into the DOM.
