### ISSUE TITLE
Middle-click still opens links when used for gestures

### ISSUE THREAD

**Issue by zsau** [marklieberman/foxygestures#79]
When using the middle mouse button for gestures, ending a gesture above a link sometimes opens that link (in addition to whatever the gesture does). This happens often when doing a forward or back gesture on top of a large link, like an image.

If the default middle-click action can't be conditionally overriden, perhaps FG could disable it altogether and then re-implement it with a "null" gesture (clicking the gesture button, with little/no movement).

**Comment by marklieberman** [comment]
Both this issue and #78 will be addressed with the changes included in the chord gestures branch.

**Comment by marklieberman** [comment]
Chord gestures branch is merged and I posted a build to the beta channel. Please try it out and let me know if #78 and #79 are resolved for you.

**Comment by zsau** [comment]
Both issues are fixed in the beta. Thanks!
