### ISSUE TITLE
Document how to manipulate DOM from user script

### ISSUE THREAD

**Issue by zsau** [marklieberman/foxygestures#80]
The README says:
> To support situations that require access to the live DOM, mouseEvents.js assigns a unique identifier to each frame in which it loads. Messages may be addressed to a specific frame using the unique frame ID.

...but I don't see how to do that from a user script. The "User Scripts" wiki page would be a good place to document this, assuming it's possible.

For reference, I'm trying to make a script that removes or hides a DOM element.

**Comment by marklieberman** [comment]
You just use regular JavaScript. User scripts run in the context where the mouse gesture happened.

**Comment by zsau** [comment]
But how do I get a reference to the object that the gesture started over? `data.element` doesn't seem to be a real DOM object.

**Comment by marklieberman** [comment]
It says in the User Scripts wiki article under "User Script Scope"

* mouseDown: A reference to the DOM element under the mouse when the gesture started.

**Comment by zsau** [comment]
Not sure how I overlooked that. Although the docs state that `mouseDown` is the element itself, while it's actually an event (so `mouseDown.target` is the element). Thanks!

**Comment by marklieberman** [comment]
I have corrected the Wiki. Thank you for letting me know.
