### ISSUE TITLE
Feature request: warn the user if webextensions.storage.sync.enabled is set to false

### ISSUE THREAD

**Issue by UserNaem** [marklieberman/foxygestures#82]
I forgot that I changed this value and the extension behaved as if it broke, no error messages, just silently ignoring any gestures (while still showing the gesture trace). The error console told me what to do, but I don't expect "regular users" to look there (or even know that the error console exists).

**Comment by marklieberman** [comment]
Why did you change it? Seems like it could break any extension using sync storage. Also, web extensions can't read about:config prefs so I have no way to check the value. I can only add more error handling to the storage.sync API usage.

**Comment by UserNaem** [comment]
I thought this has something to do with Firefox Sync and disabled it in hopes of the "Sign in to Sync" button disappearing. (And it didn't.)
Oh well, I guess no one else would be dumb enough to touch unknown about:config prefs and then have their extensions break randomly.
