### ISSUE TITLE
Zopim chatbox script breaks gestures

### ISSUE THREAD

**Issue by MisaelK** [marklieberman/foxygestures#84]
In the site [Nisuta](http://www.nisuta.com/) (an Argentine hardware manufacturer) Foxy Gestures doesn't work.

When making a Mouse Gesture, the trail is shown on the top-left border of the screen instead of under the mouse pointer, and the timeouts seem to fail completely, as the movements keep stacking on the status text even after releasing the mouse button. Waiting for the status text to disappear (both my gesture timeout and my status timeout are set to 0.5s) doesn't restart the gesture, only refreshing the page does.

[Example recording here](https://i.imgur.com/7y9MoiC.gif).

I'm using Firefox 56.0.1 (64-bit) on Windows 10 Enterprise LTSB x64, with FoxyGestures 1.0.8.

**Comment by marklieberman** [comment]
The problem coming from the chatbox at the bottom of the page. The one with the orange letter. It is interfering with the mouse events. 

The script is minified so it is difficult to debug. If you block "http://cdn.zopim.com" using uBlock or Adblock, gestures should work normally. 

I will try to investigate futher, but I'm not sure if it can be completely resolved. This is one of the problems with Web Extensions; I must share the scope with scripts from the webpage.

**Comment by MisaelK** [comment]
Thanks for your time!

Effectively, blocking the zopim domain makes gestures work without problems. The problematic script is indeed quite large to analyze what is the cause.
Curiously, on the [zopim site](https://www.zopim.com/) a similar widget (and script) appears, although Foxy Gestures works fine there. The script is a slightly different one, though ([2.220](https://v2.zopim.com/bin/v/widget_v2.220.js) vs [2.219](http://v2.zopim.com/bin/v/widget_v2.219.js)).

**Comment by marklieberman** [comment]
I was just testing this with my latest changes versus the current 1.1.0, and its broken in 1.1.0 but fixed in master so I'm going to go ahead and close this issue.
