### ISSUE TITLE
Add gesture to open Foxy Gestures option window

### ISSUE THREAD

**Issue by Serge-45** [marklieberman/foxygestures#88]
Would be great to be able to setup a gesture for opening the Foxy Gestures option window itself. Both for changing the setup and as a reminder for already configured gestures.
This kind of feature existed in Firegestures and was very helpful.

**Comment by dpesch** [comment]
You could open the option tab with this user script:

`executeInBackground(src => {
        getActiveTab(tab => browser.tabs.create({
            url: 'moz-extension://5b4d8bcf-9361-4dcf-a6a6-07b4ecc756a6/options/options.html',
            index: tab.index + 1,
            active: true
        }));
}, [])`

**Comment by Serge-45** [comment]
Thanks a lot for this script. I had to change the ID to have it working. I replaced it by 90ce75e6-8669-4276-abeb-3aebd76338e1.
I found this ID when looking at the source code of the option page using the DOM inspector. May be different for each user ?
