### ISSUE TITLE
How to create gestures of sending key event?

### ISSUE THREAD

**Issue by coolingx** [marklieberman/foxygestures#89]
I'm using NextPage@slimx.user.js which provides page turning by key LEFT or RIGHT. So I want to create a gesture that send key LEFT or RIGHT event to NextPage@slimx.user.js. 
But I'm poor at progamming. Can you help me? Thanks!

**Comment by marklieberman** [comment]
You didn't provide a link to the source code of that user script and Google did not give me any English language results.

You can try adding a user script to Foxy Gestures that [dispatches a keyboard event](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent) to mouseDown.target.

It would look something like this
```
var kbEvent = new KeyboardEvent('keydown',{ key: 'ArrowLeft' });
mouseDown.target.dispatchEvent(kbEvent);
```

**Comment by coolingx** [comment]
I've put your code to new gesture,but it didn't work. 
Now I'm using a similar user script. It's link is [https://github.com/ywzhaiqi/userscript/tree/master/scripts/NextPage].
Please help me, give me the hold code. Thanks!

**Comment by marklieberman** [comment]
I didn't test it, but try this:
```js
let nextPageEvent = new Event('nextpage.go');
document.dispatchEvent(nextPageEvent); 
```
and
```js
let nextPageEvent = new Event('nextpage.back');
document.dispatchEvent(nextPageEvent); 
```
