### ISSUE TITLE
How to create gestures?

### ISSUE THREAD

**Issue by doobersn** [marklieberman/foxygestures#9]
Hello! I used to use firegestures but switched to this one. Can I make gestures for next tab, previous tab, new blank window, new blank tab in foreground, close all other tabs, etc? Like firegestures, I guess. Thank you!

**Comment by marklieberman** [comment]
Next tab and previous tab commands are already implemented. See #6. You can create any command you want with User Scripts. See #1 and #5. I may also add the functions you mentioned as built in commands.

All of those features are coming in the next version but it will probably be a few weeks to finalize everything and pass review on AMO.

**Comment by doobersn** [comment]
Hmm, I definitely do not see next or previous tabs: http://i.imgur.com/YcQ4n1r.jpg Thank you very much for emailing me back! Ill try to learn how to create gestures.

Best wishes!

**Comment by marklieberman** [comment]
It will be in the next version. It is not in the current version.
