### ISSUE TITLE
suggest that commands can be called by severl gestures

### ISSUE THREAD

**Issue by coolingx** [marklieberman/foxygestures#90]
I think many users would like some commands can be called by severl gestures so they're no need to remember exactly.
They can use DR or DL to close one tab, use LR or RL to resume tab ,etc.
I suggest that built-in commands can be easily chosen to creat a new gesture.

**Comment by marklieberman** [comment]
I've already decided not to support this feature. See: #54. There are workarounds if you really need it. Add a user script, bind it to the second gesture, and have the script call the built in command. See: #40.
