### ISSUE TITLE
Built-in Commands Option page unresponsive

### ISSUE THREAD

**Issue by buildersbrewery** [marklieberman/foxygestures#92]
Since the last update to Foxy Gestures, I cannot input new gestures via the Built-in Commands Option page.

* Foxy Gestures: v1.0.9
* Firefox v56.0.2 x64 (portable)
* Waterfox v55.2.2 x64 (portable)
* Win10 Pro x64 Version 1709

**Comment by marklieberman** [comment]
Can you open the browse console (ctrl+shift+J) and then open the Foxy Gestures options and tell me if an error appears in the console?

**Comment by buildersbrewery** [comment]
@marklieberman Thanks, works again in both foxes.
