### ISSUE TITLE
Can't select text when using left button for gestures

### ISSUE THREAD

**Issue by tmarkov** [marklieberman/foxygestures#95]
I used to be able to use the left button for both gestures and to select text (both would happen when I start a gesture). But, with a recent update, it no longer works that way. I guess it's the update which added the option to use alt key to suppress gestures, since now we can use alt to select.

However, I'm using this extension with a touchscreen stylus, i.e. no alt key. Can I somehow get the latest version that still does both gesture and text select? I tried this, https://addons.mozilla.org/en-US/firefox/addon/foxy-gestures/versions/, but all versions between 1.0.2 and 1.0.9 are missing there.

Thanks

**Comment by marklieberman** [comment]
@tmarkov There's an option for this now so be sure to go back to using updates

**Comment by tmarkov** [comment]
Thanks
