### ISSUE TITLE
Gestures not resetting properly

### ISSUE THREAD

**Issue by agentaces** [marklieberman/foxygestures#96]
Whatever isn't drawn when you release the gesture button is stored until another gesture is attempted. This can be enough to add an incorrect input to a gesture. This behavior was added in version 1.0.9 and still exists in 1.0.10
![gif](https://user-images.githubusercontent.com/33503490/32584367-90e75b3e-c4bd-11e7-9c45-02fe9e0ebe73.gif)

**Comment by marklieberman** [comment]
I'm pretty sure I know whats wrong, its a bug related to #86. I will publish a fix as soon as I have some free time.
