### ISSUE TITLE
clipboardWrite

### ISSUE THREAD

**Issue by BHButcher** [marklieberman/foxygestures#97]
I was using **FireGestures:HybridCopyURL**, I know it's hybrid and it's not supported, but I only use it to copy link URLs. After a bit of internet searching I came up with this script, but it's not working. I think the extension must have de **clipboardWrite** permission for it to work, ¿right?

```javascript
var src = data.element && data.element.linkHref;
if (src) {
    executeInBackground(src => {
        var copyLink = document.getElementById("copyLinkTextArea");
        if (!copyLink) {
            copyLink = document.createElement("TEXTAREA");
            copyLink.id = "copyLinkTextArea";
            document.body.appendChild(copyLink);
        }
        copyLink.value = src;
        copyLink.select();
        document.execCommand("copy");
    }, [ src ]);
}
```

Thanks in advance for your time.

**Comment by marklieberman** [comment]
I came up with this script that seems to work well using the information from this [StackOverflow](https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript) post. However, it does require the `clipboardWrite` permission so I will have to request it in the next version.

```js
let src = data.element && data.element.linkHref;
if (src) {
    // Create a text area with the value we want to copy.
    let textarea = document.createElement("textarea");
    textarea.value = src;
    
    // Style textarea to make it fairly invisible.
    // Copy doesn't work when display: none.
    textarea.style.maxHeight = '2em';
    textarea.style.maxWidth = '2em';
    textarea.style.position = 'fixed';
    textarea.style.top = 0;
    textarea.style.left = 0;
    textarea.style.padding = 0;
    textarea.style.border = 'none';
    textarea.style.outline = 'none';
    textarea.style.boxShadow = 'none';
    textarea.style.background = 'transparent';
    
    // Append the textarea, copy its value, then remove it.
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand("copy");
    textarea.remove();
    
    // Update status text for gesture.
    setStatus('Copied: ' + src);
}
```

**Comment by yfdyh000** [comment]
@marklieberman FYI: https://github.com/mdn/webextensions-examples/blob/master/context-menu-copy-link-with-types/clipboard-helper.js for `optionalPermissionClipboardWriteSummary`: "Currently the API only supports copying images, but it's intended to support copying text and HTML in the future."

**Comment by YandLiu** [comment]
I deleted my Firefox profile folder accidentally, but fortunately I have an exported config backup of this extension, however I found after I imported extension settings, this script can't work anymore, and I'm 100% sure it worked fine right before I deleted my profile. I'm currently using a blank profile in the newest Firefox release with the newest Foxy Gestures. Could you tell me why?
