### ISSUE TITLE
Scroll tabs with mouse wheel

### ISSUE THREAD

**Issue by Coksnuss** [marklieberman/foxygestures#98]
I am currently searching for a FF57+ alternative of the [Mouse Gestures Suite](https://github.com/lemon-juice/mouse-gestures-suite). Just tried foxygestures and for now I am quite happy with it (besides the usual shortcommings such as non-working geastures on the addon page, blank tabs or within other UI elements of firefox)

I was wondering if it is possible (at least in theory) with WebExtension to allow scrolling of tabs with the mouse wheel (while hovering the tab bar). I doubt that this is possible, but I wanted to give it a try. However, if it is possible then I would love to see this feature implemented in foxygestures.

**Comment by marklieberman** [comment]
Its not currently possible to get events from the tab bar using Web Extensions. In fact, Mozilla isn't really keen on supporting tab switching with the wheel. Here's some threads about it on Reddit: https://www.reddit.com/r/firefox/search?q=tab+wheel&restrict_sr=on&sort=relevance&t=all

**Comment by fenjen** [comment]
You can use [Tree Style Tabs](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/) along with [Tree Style Tab Mouse Wheel](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab-mouse-wheel/) or [Sidebery](https://addons.mozilla.org/en-US/firefox/addon/sidebery/).

**Comment by schnz** [comment]
Although I appreciate the effort, this ticket is (almost to the day) 7 years old by now and my workflow on how I browse the web has completely changed at this point.
